project_id = "wnwfnziozwarlihrnjex"

[functions.process-withdrawal]
verify_jwt = true

[functions.anubis-auth]
verify_jwt = false

[functions.send-2fa-code]
verify_jwt = false

[functions.upload-vault-file]
verify_jwt = false

[functions.list-vault-files]
verify_jwt = false

[functions.download-vault-file]
verify_jwt = false

[functions.delete-vault-file]
verify_jwt = false

[functions.webrtc-signaling]
verify_jwt = false