import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type AppLanguage = "both" | "ar" | "en" | "ru";

interface LanguageLabels {
  native: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: Record<AppLanguage, LanguageLabels> = {
  both: { native: "عربي + English", flag: "🌍" },
  ar: { native: "العربية", flag: "🇪🇬" },
  en: { native: "English", flag: "🇬🇧" },
  ru: { native: "Русский", flag: "🇷🇺" },
};

type TranslationKey = string;
type Translations = Record<AppLanguage, Record<TranslationKey, string>>;

const translations: Translations = {
  both: {},
  ar: {},
  en: {
    // ---- Navigation ----
    "الرئيسية": "Home",
    "المحفظة": "Wallet",
    "التعلم": "Learning",
    "الاستبيانات": "Surveys",
    "البروفايل": "Profile",
    "تسجيل الخروج": "Sign Out",
    "تسجيل الدخول": "Sign In",
    "انضم الآن": "Join Now",
    "التنقل الرئيسي": "Main Navigation",
    "الوصول المبكر": "Early Access",
    "لوحة التحكم": "Admin Panel",
    "رسالة جديدة": "New Message",
    "البث المباشر": "Live Streams",
    "التعدين": "Mining",
    "الهوية": "Identity",
    "المستندات": "Documents",
    "التحديثات": "Updates",
    "الدعم": "Support",
    "العملة المستقرة": "StableCoin",
    "المهام اليومية": "Daily Tasks",
    "الريلز": "Reels",
    "خريطة الطريق": "Roadmap",
    "أنوبيس": "Anubis",
    "الاشتراك": "Subscription",

    // ---- Platform names ----
    "منصة مصر الرقمية": "Egypt Digital Platform",
    "منصة مصر": "Egypt Platform",
    "مصر": "MSR",

    // ---- Common UI ----
    "جاري التحميل...": "Loading...",
    "جاري التحقق من الصلاحيات...": "Checking permissions...",
    "جاري التحميل": "Loading",
    "يرجى تسجيل الدخول": "Please sign in",
    "للوصول إلى المحفظة": "to access your wallet",
    "غير مصرح": "Unauthorized",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "You don't have permission to access this page",
    "إعادة تحميل الصفحة": "Reload Page",
    "المحاولة مرة أخرى": "Try Again",
    "حدث خطأ غير متوقع": "An unexpected error occurred",
    "عذراً، حدث خطأ في التطبيق. يرجى إعادة تحميل الصفحة.": "Sorry, an error occurred. Please reload the page.",
    "تفاصيل الخطأ": "Error Details",
    "قريباً": "Coming Soon",

    // ---- Actions ----
    "حفظ": "Save",
    "إلغاء": "Cancel",
    "تأكيد": "Confirm",
    "إرسال": "Send",
    "تحديث": "Update",
    "حذف": "Delete",
    "إضافة": "Add",
    "تعديل": "Edit",
    "بحث": "Search",
    "عرض": "View",
    "رفع": "Upload",
    "تنزيل": "Download",
    "نسخ": "Copy",
    "مشاركة": "Share",
    "موافق": "OK",
    "رفض": "Reject",
    "قبول": "Accept",
    "تحويل": "Convert",
    "سحب": "Withdraw",

    // ---- Status ----
    "نشط": "Active",
    "غير نشط": "Inactive",
    "معلق": "Pending",
    "مكتمل": "Completed",
    "مرفوض": "Rejected",
    "موافق عليه": "Approved",
    "قيد المراجعة": "Under Review",
    "منتهي": "Expired",
    "متوقف": "Stopped",
    "قيد التنفيذ": "Processing",
    "فشل": "Failed",

    // ---- Auth page ----
    "إنشاء حساب جديد": "Create New Account",
    "الاسم الكامل": "Full Name",
    "البريد الإلكتروني": "Email",
    "كلمة المرور": "Password",
    "رقم الهاتف": "Phone Number",
    "الدخول بـ Google": "Sign in with Google",
    "ليس لديك حساب؟": "Don't have an account?",
    "لديك حساب بالفعل؟": "Already have an account?",
    "تم تسجيل الدخول بنجاح": "Signed in successfully",
    "مرحباً بك في منصة مصر": "Welcome to Egypt Platform",
    "فشل تسجيل الدخول": "Sign in failed",
    "تحقق من البيانات": "Check your credentials",
    "تم إنشاء الحساب": "Account created",
    "تحقق من بريدك لتفعيل الحساب": "Check your email to activate your account",
    "تعذر إنشاء الحساب": "Failed to create account",
    "إنشاء حساب": "Create Account",
    "حساب جديد": "New Account",
    "جاري الدخول...": "Signing in...",
    "دخول": "Sign In",
    "جاري إنشاء الحساب...": "Creating account...",
    "أو": "or",
    "تسجيل الدخول بـ Google": "Sign in with Google",
    "التسجيل بـ Google": "Sign up with Google",
    "تسجيل الدخول عبر Telegram": "Sign in via Telegram",
    "التسجيل عبر Telegram": "Sign up via Telegram",
    "أو الدخول بالمحفظة": "or sign in with wallet",
    "أو التسجيل بالمحفظة": "or sign up with wallet",
    "فشل تسجيل الدخول بـ Google": "Google sign in failed",
    "حدث خطأ، حاول مرة أخرى": "An error occurred, try again",
    "التسجيل عبر تيليجرام سيكون متاحاً قريباً": "Telegram login will be available soon",
    "تسجيل الدخول عبر تيليجرام سيكون متاحاً قريباً": "Telegram login will be available soon",
    "ربط محفظة Solana سيكون متاحاً قريباً": "Solana wallet connection coming soon",
    "ربط محفظة EVM سيكون متاحاً قريباً": "EVM wallet connection coming soon",
    "ربط محفظة TON سيكون متاحاً قريباً": "TON wallet connection coming soon",
    "ربط محفظة Solana": "Connect Solana wallet",
    "ربط محفظة EVM": "Connect EVM wallet",
    "ربط محفظة TON": "Connect TON wallet",

    // ---- Wallet ----
    "الرصيد": "Balance",
    "استقبال": "Receive",
    "استلام": "Receive",
    "تاريخ المعاملات": "Transaction History",
    "المعاملة": "Transaction",
    "المبلغ": "Amount",
    "التاريخ": "Date",
    "الحالة": "Status",
    "عنوان المحفظة": "Wallet Address",
    "شحن المحفظة": "Recharge Wallet",
    "حوّل نقاطك إلى MS-RA": "Convert your points to MS-RA",
    "سحب إلى محفظة خارجية": "Withdraw to External Wallet",
    "المحافظ الخارجية": "External Wallets",
    "المكافآت": "Rewards",
    "قريباً ستتمكن من ربح مكافآت إضافية": "You'll be able to earn extra rewards soon",
    "تبديل العملات": "Swap Tokens",
    "استلام العملات": "Receive Tokens",
    "إرسال العملات": "Send Tokens",
    "قم بتوصيل محفظة Solana أو EVM لعرض عنوان الاستلام": "Connect a Solana or EVM wallet to display your receive address",
    "قم بتوصيل محفظة خارجية لإرسال العملات": "Connect an external wallet to send tokens",
    "لا توجد معاملات": "No transactions",
    "ستظهر معاملاتك هنا": "Your transactions will appear here",
    "مركز التبادل": "Exchange Center",
    "ميزة الربح قادمة قريباً!": "Earning feature coming soon!",
    "إضافة عملات مخصصة قادمة قريباً": "Custom token addition coming soon",
    "اربح": "Earn",
    "تبديل": "Swap",
    "العملات": "Tokens",
    "قم بإيداع عملات من محفظة أخرى أو منصة تداول": "Deposit crypto from wallet or exchange",
    "إضافة عملة": "Add Token",
    "لا توجد NFTs حالياً": "No NFTs found",
    "فرص الربح قادمة قريباً": "Earning opportunities coming soon",
    "نقاط الخبرة": "Experience Points",
    "المحفظة الداخلية": "Internal Wallet",

    // ---- Profile ----
    "تعديل البروفايل": "Edit Profile",
    "الاسم": "Name",
    "البيو": "Bio",
    "المتابعون": "Followers",
    "المتابَعون": "Following",
    "الإنجازات": "Achievements",
    "حساب موثق": "Verified Account",
    "تغيير الصورة": "Change Photo",
    "البروفايل غير متوفر": "Profile not available",
    "لم يتم العثور على بيانات البروفايل": "Profile data not found",
    "نظرة عامة": "Overview",
    "عامة": "Overview",
    "العائلة": "Family",
    "عائلة": "Family",
    "تحرير": "Edit",
    "النشاط": "Activity",
    "نشاط": "Activity",
    "الإعدادات": "Settings",
    "إعدادات": "Settings",
    "معلومات الملف الشخصي": "Profile Info",
    "غير محدد": "Not specified",
    "تاريخ الانضمام": "Join Date",
    "اللغة المفضلة": "Preferred Language",
    "العربية": "Arabic",
    "روابط التواصل": "Social Links",
    "الموقع الشخصي": "Personal Website",
    "لا توجد روابط متاحة": "No links available",
    "البادجات": "Badges",
    "نقاط الخبرة": "Experience Points",
    "إجمالي النقاط": "Total Points",
    "رصيد XP": "XP Balance",
    "المحافظ المربوطة": "Connected Wallets",
    "لا توجد محافظ مربوطة": "No wallets connected",
    "الاستبيانات المكتملة": "Completed Surveys",
    "لم يتم إكمال أي استبيان بعد": "No surveys completed yet",
    "سجل النشاط": "Activity Log",
    "تتبع نشاطاتك الأخيرة على المنصة": "Track your recent platform activity",
    "لا توجد أنشطة مسجلة حتى الآن": "No activities recorded yet",
    "إعدادات الحساب": "Account Settings",
    "إدارة إعدادات الخصوصية والأمان": "Manage privacy and security settings",
    "إعدادات الخصوصية": "Privacy Settings",
    "التحكم في من يمكنه رؤية معلوماتك": "Control who can see your information",
    "الأمان": "Security",
    "تغيير كلمة المرور والمصادقة الثنائية": "Change password & two-factor authentication",
    "الإشعارات": "Notifications",
    "إدارة تفضيلات الإشعارات": "Manage notification preferences",
    "المتابعات": "Follows",
    "متابع": "Followers",
    "يتابع": "Following",

    // ---- Mining ----
    "بدء التعدين": "Start Mining",
    "إيقاف التعدين": "Stop Mining",
    "معدل التعدين": "Mining Rate",
    "إجمالي التعدين": "Total Mined",
    "مستوى التعدين": "Mining Level",
    "لوحة التعدين": "Mining Dashboard",
    "تتبع تقدم التعدين وقوة حسابك": "Track your mining progress & account strength",
    "تم التحديث": "Updated",
    "فشل في تحديث التعدين": "Failed to update mining",
    "تم إيقاف التعدين": "Mining stopped",
    "التعدين متوقف الآن": "Mining is now stopped",
    "تم تشغيل التعدين": "Mining started",
    "التعدين يعمل الآن": "Mining is now active",
    "فشل في تغيير حالة التعدين": "Failed to change mining status",
    "جاري تحميل بيانات التعدين...": "Loading mining data...",
    "إعادة المحاولة": "Retry",
    "قوة الحساب": "Account Strength",
    "نقطة": "Points",
    "المستوى الحالي": "Current Level",
    "حالة التعدين": "Mining Status",
    "التعدين منذ:": "Mining since:",
    "جاري التحديث...": "Updating...",
    "تحديث الآن": "Update Now",
    "التعدين الحالي": "Current Mining",
    "سيتم إضافتها عند التحديث التالي": "Will be added on next update",
    "تقدم المستوى": "Level Progress",
    "الحد الأقصى": "Maximum",
    "القوة المطلوبة:": "Required Strength:",
    "المستوى التالي": "Next Level",
    "التعدين خلال 24 ساعة": "24h Mining History",
    "لا توجد بيانات تعدين خلال الـ 24 ساعة الماضية": "No mining data in the last 24 hours",
    "مستويات التعدين": "Mining Levels",
    "المستوى": "Level",
    "المعدل": "Rate",
    "القوة": "Strength",
    "معدل التعدين:": "Mining Rate:",
    "تكلفة الترقية:": "Upgrade Cost:",
    "بدء": "Start",
    "إيقاف": "Stop",

    // ---- Support ----
    "إرسال رسالة": "Send Message",
    "موضوع الرسالة": "Subject",
    "نص الرسالة": "Message",
    "الرسائل المرسلة": "Sent Messages",
    "رد الدعم": "Support Reply",
    "إرسال الرسالة": "Send Message",
    "الموضوع": "Subject",
    "الأولوية": "Priority",
    "الرسالة": "Message",
    "منخفض": "Low",
    "عادي": "Normal",
    "عالي": "High",
    "عاجل": "Urgent",
    "تم إرسال الرسالة": "Message sent",
    "سيتم الرد عليك في أقرب وقت ممكن": "We'll respond as soon as possible",
    "جاري الإرسال...": "Sending...",
    "رسائلك السابقة": "Previous Messages",
    "لا توجد رسائل سابقة": "No previous messages",
    "رسالتك:": "Your message:",
    "رد الإدارة:": "Admin Response:",
    "قيد الانتظار": "Pending",
    "قيد المعالجة": "Processing",
    "تم الحل": "Resolved",
    "مغلق": "Closed",

    // ---- Learning ----
    "الدروس": "Lessons",
    "المقالات": "Articles",
    "الفيديوهات": "Videos",
    "اختبار": "Quiz",
    "الدرجة": "Score",
    "اجتاز": "Passed",
    "رسب": "Failed",
    "المنصة التفاعلية": "Interactive Platform",
    "تعلم، شارك، وتفاعل مع مجتمع المتداولين والمستثمرين في العملات الرقمية": "Learn, share, and engage with the crypto trading & investing community",
    "شارك محتوى تعليمي": "Share educational content",
    "رسالة المنصة": "Platform Message",
    "السابقة": "Previous",
    "التالية": "Next",
    "مالي": "Financial",
    "عام": "General",
    "ديني": "Religious",
    "إنشاء منشور جديد": "Create new post",
    "إنشاء منشور تعليمي": "Create educational post",
    "عنوان المنشور": "Post title",
    "محتوى المنشور": "Post content",
    "نوع المحتوى": "Content type",
    "نص": "Text",
    "صورة": "Image",
    "فيديو": "Video",
    "صوت": "Audio",
    "مختلط": "Mixed",
    
    "مستوى الصعوبة": "Difficulty level",
    "مبتدئ": "Beginner",
    "متوسط": "Intermediate",
    "متقدم": "Advanced",
    "القسم": "Section",
    "العلامات (مفصولة بفواصل)": "Tags (comma separated)",
    "نشر المحتوى": "Publish content",
    "مؤلف مجهول": "Unknown author",
    "ثنائي اللغة": "Bilingual",
    "مجهول": "Anonymous",
    "اكتب تعليقاً...": "Write a comment...",
    "حدث خطأ في جلب المنشورات": "Error fetching posts",
    "يرجى إدخال عنوان المنشور": "Please enter a post title",
    "تم إنشاء المنشور": "Post created",
    "تم إنشاء المنشور بنجاح": "Post created successfully",
    "حدث خطأ في إنشاء المنشور": "Error creating post",

    // ---- Surveys ----
    "الاستبيان": "Survey",
    "الأسئلة": "Questions",
    "الإجابات": "Answers",
    "إرسال الاستبيان": "Submit Survey",
    "لم يكتمل": "Incomplete",

    // ---- Early Access ----
    "طلب الوصول المبكر": "Request Early Access",
    "في انتظار الموافقة": "Awaiting Approval",
    "تم قبولك": "You've been accepted",
    "لم تتم الموافقة بعد": "Not approved yet",
    "شكراً لتسجيلك في منصة مصر": "Thank you for registering at Egypt Platform",
    "نحن نعمل حالياً على الإطلاق الرسمي للمنصة. سيتم إشعارك عبر البريد الإلكتروني فور إتاحة الوصول الكامل.": "We're currently working on the official platform launch. You'll be notified via email once full access is available.",
    "نقدر صبرك وثقتك بنا": "We appreciate your patience and trust",

    // ---- Live Stream ----
    "بث مباشر": "Live Stream",
    "شاهد البث": "Watch Stream",
    "بدء البث": "Start Streaming",
    "إنهاء البث": "End Stream",
    "المشاهدون": "Viewers",
    "تعليق": "Comment",
    "التعليقات": "Comments",

    // ---- Daily Tasks ----
    "المهام | Tasks": "Tasks",
    "أكمل مهامك اليومية لتحصل على النقاط وتبني سلسلة حضورك المتتالي": "Complete your daily tasks to earn points and build your streak",
    "السلسلة:": "Streak:",
    "أطول سلسلة:": "Best Streak:",
    "الجلسات:": "Sessions:",
    "مهامك اليومية": "Your Daily Tasks",
    "قرآن": "Quran",
    "شخصية": "Personality",
    "يومية": "Daily",
    "عجلة الحظ": "Wheel of Fortune",
    "مرحباً بك في المهام اليومية": "Welcome to Daily Tasks",
    [`الانتظام في آداء المهام ،،، و تنظيم الوقت ...هو تدريب علي الأنضباط و المثابرة
لذلك الصدق و النزاهة هم لمصلحتك ...اما الغش و الخداع يجعلك متأخرا ليس أكثر..
.لانه بعد بضع اسابيع ستري تأثير الصدق والالتزام علي كل جوانب حياتك`]: "Consistency in completing tasks and organizing your time is training in discipline and perseverance. Honesty and integrity serve your own growth, while cheating only delays you. After a few weeks, you will notice the impact of honesty and commitment across every part of your life.",
    "المهام العامة": "General Tasks",
    [`تسجيل حضورك بشكل يومي في توقيت محدد... يعزز انتمائك للمنصة... و يعطيك مؤشر علي قدرتك علي الالتزام  و المثابرة و الانضباط... وهو كل ما يتطلبه النجاح في كل مكان و في كل الظروف و يفتح الطريق لمعرفة امكانياتك بشكل افضل... انشاءك قائمة المهام اليومية الخاصة بك و تثبيت مواقيت لانجازها... يعطي مؤشر ممتاز،. سواء نجحت في الالتزام بها ام لا.... فهذا ما يفعله كل رواد الاعمال و الناجحين حول العالم`]: "Showing up daily at a fixed time strengthens your connection to the platform and reflects your ability to commit, persevere, and stay disciplined. Building your own daily task list and sticking to clear times is a strong indicator of growth—this is what successful founders and achievers around the world do.",
    "محتوى الوسائط": "Media Content",
    "اطلع على أحدث المحتوى التعليمي والإعلامي": "Explore the latest educational and media content",

    // ---- Admin ----
    "إدارة المستخدمين": "Users Management",
    "إدارة الوصول المبكر": "Early Access Management",
    "رسائل الدعم": "Support Messages",
    "إدارة الحسابات المعتمدة": "Verified Accounts",
    "إدارة الهوية": "Identity Management",
    "إدارة الاستبيانات": "Surveys Management",
    "إدارة التعلم": "Learning Management",
    "إدارة محتوى التطبيق": "App Content Management",
    "إدارة التحديثات": "Updates Management",
    "إدارة مستويات التعدين": "Mining Levels Management",
    "إدارة مواقع المتعاونين": "Market Locations Management",
    "إدارة الإعلانات": "Announcements Management",
    "إدارة البادجات": "Badges Management",
    "إدارة كارت أنوبيس": "Anubis Card Management",
    "إدارة الاستدعاء النشط": "Active Callout Management",
    "قائمة الاستدعاء الشرفية": "Honor Callout List",
    "إحصائيات التفاعل": "Engagement Stats",
    "المهام اليومية (إدارة)": "Daily Tasks Management",
    "إدارة صفحات القرآن": "Quran Pages Management",
    "إدارة الوسائط": "Media Management",
    "مهام تطوير الشخصية": "Personality Tasks",
    "إدارة مقدمات المهام": "Task Introductions",
    "إدارة أقسام الريلز": "Reels Categories",
    "إدارة كارت الاستدعاء": "Callout Card Management",
    "إعدادات التحويل": "Conversion Settings",
    "إدارة كروت الرودماب": "Roadmap Cards",
    "إدارة بطاقات الصفحة الرئيسية": "Home Page Cards",
    "إعدادات البروفايل": "Profile Settings",
    "إدارة طلبات البث المباشر": "Live Stream Approvals",
    "إدارة العملات الداخلية": "Internal Tokens",
    "إدارة مجمع السيولة": "Liquidity Pool",
    "إدارة عجلة الحظ": "Wheel of Fortune",
    "إدارة طلبات العائلة": "Family Requests",
    "إدارة رسالة المنصة": "Platform Message",

    // ---- Errors ----
    "خطأ": "Error",
    "حدث خطأ": "An error occurred",
    "فشل في التحميل": "Failed to load",
    "فشل في الحفظ": "Failed to save",
    "فشل في الإرسال": "Failed to send",
    "فشل في تحميل البروفايل": "Failed to load profile",

    // ---- Success ----
    "تم بنجاح": "Done successfully",
    "تم الحفظ": "Saved",
    "تم الإرسال": "Sent",

    // ---- Misc ----
    "الدفع بـ Pi": "Pay with Pi",
    "إعادة الشحن": "Recharge",
    "الإعلانات": "Announcements",
    "التوثيق": "Verification",
    "الخصوصية": "Privacy",
    "سياسة الخصوصية": "Privacy Policy",
    "استبيان": "Survey",
    "محفظة العملات الرقمية": "Digital Crypto Wallet",
    "منصة بسيطة للعملات الرقمية مع محفظة آمنة وتوثيق الهوية": "A simple crypto platform with secure wallet and identity verification",

    // ---- Identity Verification ----
    "توثيق الهوية": "Identity Verification",
    "عملية التحقق من الهوية (KYC) تضمن أمان حسابك والامتثال للمعايير المطلوبة. يرجى تقديم بيانات دقيقة ومطابقة للوثائق الرسمية.": "The KYC identity verification process ensures your account security and compliance with required standards. Please provide accurate data matching your official documents.",
    "تحذير مهم": "Important Warning",
    "حالة التحقق الحالية": "Current Verification Status",
    "تم التحقق": "Verified",
    "مسودة": "Draft",
    "ملاحظات": "Notes",
    "تاريخ الطلب": "Request Date",
    "آخر تحديث": "Last Update",
    "المعلومات الشخصية": "Personal Information",
    "أدخل معلوماتك الشخصية الصحيحة والمطابقة للوثائق الرسمية": "Enter accurate personal details matching your official documents",
    "تاريخ الميلاد": "Date of Birth",
    "الجنسية": "Nationality",
    "العنوان الكامل": "Full Address",
    "حفظ والمتابعة": "Save & Continue",
    "جاري الحفظ...": "Saving...",
    "بيانات ناقصة": "Missing Data",
    "يرجى ملء جميع الحقول المطلوبة": "Please fill all required fields",
    "تم حفظ البيانات": "Data Saved",
    "تم حفظ معلوماتك الشخصية بنجاح": "Your personal information has been saved successfully",
    "خطأ في الحفظ": "Save Error",
    "حدث خطأ أثناء حفظ البيانات": "An error occurred while saving data",
    "رفع الوثائق": "Upload Documents",
    "اختر نوع الوثيقة وأدخل رقمها": "Select document type and enter its number",
    "نوع الوثيقة": "Document Type",
    "اختر نوع الوثيقة": "Select Document Type",
    "رقم الوثيقة": "Document Number",
    "أدخل رقم الوثيقة": "Enter document number",
    "الهوية الوطنية": "National ID",
    "جواز السفر": "Passport",
    "رخصة القيادة": "Driving License",
    "الإقامة": "Residence Permit",
    "صورة الوثيقة - الوجه الأمامي": "Document Photo - Front Side",
    "صورة الوثيقة - الوجه الخلفي (اختياري)": "Document Photo - Back Side (Optional)",
    "صورة شخصية مع حمل الوثيقة": "Selfie holding the document",
    "اضغط لرفع الصورة": "Click to upload photo",
    "فتح الكاميرا": "Open Camera",
    "رفع صورة": "Upload Photo",
    "إزالة الصورة": "Remove Photo",
    "اختر طريقة إضافة الصورة": "Choose how to add the photo",
    "جاري الرفع...": "Uploading...",
    "متطلبات الوثائق:": "Document Requirements:",
    "السابق": "Previous",
    "إرسال للمراجعة": "Submit for Review",
    "الوثائق مطلوبة": "Documents Required",
    "يرجى رفع صورة الوثيقة والصورة الشخصية": "Please upload the document photo and selfie",
    "يرجى اختيار نوع الوثيقة وإدخال رقمها": "Please select document type and enter its number",
    "تم إرسال الطلب": "Request Submitted",
    "تم إرسال طلب التحقق من الهوية للمراجعة": "Identity verification request submitted for review",
    "خطأ في الإرسال": "Submission Error",
    "حدث خطأ أثناء رفع الوثائق": "An error occurred while uploading documents",
    "مراجعة الطلب": "Request Review",
    "تم استلام طلبك وهو قيد المراجعة من قبل فريقنا": "Your request has been received and is being reviewed by our team",
    "طلبك قيد المراجعة": "Your request is under review",
    "يستغرق التحقق من الهوية عادة من 1-3 أيام عمل. سنقوم بإشعارك فور اكتمال المراجعة.": "Identity verification usually takes 1-3 business days. You'll be notified when the review is complete.",
    "ملخص الطلب:": "Request Summary:",
    "ماذا بعد؟": "What's Next?",
    "سبب الرفض:": "Rejection Reason:",
    "إعادة تقديم الطلب": "Re-submit Request",
    "تم التحقق في:": "Verified on:",

    // ---- Live Stream Page ----
    "منصة البث المباشر": "Live Streaming Platform",
    "للأعضاء المعتمدين والمؤثرين والمشاهير": "For verified members, influencers and celebrities",
    "شاهد البثوث المباشرة للآخرين": "Watch others' live streams",
    "حالة الطلب": "Application Status",
    "معتمد": "Approved",
    "تاريخ التقديم": "Submission Date",
    "تاريخ المراجعة": "Review Date",
    "سبب الرفض": "Rejection Reason",
    "تم اعتماد حسابك - ابدأ البث الآن!": "Your account is approved - Start streaming now!",
    "يمكنك الآن بدء البث المباشر من التطبيق مباشرة": "You can now start live streaming directly from the app",
    "تقديم طلب الاعتماد": "Submit Approval Request",
    "يرجى ملء البيانات التالية للحصول على موافقة الإدارة": "Please fill in the following data to get admin approval",
    "الاسم الكامل *": "Full Name *",
    "البريد الإلكتروني *": "Email *",
    "روابط وسائل التواصل الاجتماعي": "Social Media Links",
    "إضافة رابط": "Add Link",
    "عدد المتابعين": "Follower Count",
    "نبذة عنك ولماذا تريد البث المباشر *": "About you and why you want to live stream *",
    "سيتم مراجعة طلبك من قبل الإدارة، وسيتم إشعارك بالقرار عبر البريد الإلكتروني": "Your request will be reviewed by admin, and you'll be notified by email",
    "يجب تسجيل الدخول أولاً": "You must sign in first",
    "تم إرسال الطلب بنجاح": "Request submitted successfully",
    "سيتم مراجعة طلبك من قبل الإدارة قريباً": "Your request will be reviewed by admin soon",
    "فشل في إرسال الطلب": "Failed to submit request",
    "إرسال الطلب": "Submit Request",
    "يجب تسجيل الدخول للوصول إلى منصة البث المباشر": "You must sign in to access the live streaming platform",

    // ---- Updates Page ----
    "آخر التحديثات": "Latest Updates",
    "تابع آخر الأخبار والتحديثات في منصة Crypto-MSR": "Follow the latest news and updates on Crypto-MSR",
    "تحديث جديد": "New Update",
    "جديد": "New",
    "اقرأ المزيد": "Read More",
    "لا توجد تحديثات حالياً": "No updates currently",
    "سيتم إضافة التحديثات هنا عند توفرها": "Updates will be added here when available",
    "المزيد من التحديثات قريباً": "More updates coming soon",
    "نعمل باستمرار على تطوير المنصة وإضافة ميزات جديدة": "We're continuously working on developing the platform and adding new features",

    // ---- Surveys Page ----
    "الاستبيانات (Surveys)": "Surveys",
    "شاركنا آراءك وساهم في تحسين تجربة المستخدمين على منصتنا.": "Share your opinions and help improve the user experience on our platform.",
    "يجب تسجيل الدخول للمشاركة في الاستبيانات": "You must sign in to participate in surveys",
    "لا توجد استبيانات نشطة حالياً.": "No active surveys currently.",
    "أسئلة": "questions",
    "عدة أسئلة": "Several questions",

    // ---- Home Cards & Components ----
    "أنوبيس - حامي الأسرار": "Anubis - Guardian of Secrets",
    "اضغط لاكتشاف أسرار أنوبيس القديمة": "Tap to discover the ancient secrets of Anubis",
    "للأعضاء المعتمدين والمؤثرين": "For verified members and influencers",
    "يتطلب دعوة أو موافقة إدارية": "Requires invitation or admin approval",
    "شاهد مجموعة مختارة من الفيديوهات التعليمية القصيرة": "Watch a curated selection of short educational videos",
    "إجمالي التعدين العالمي": "Global Mining Progress",
    "من": "of",
    "معدّن نشط": "active miners",
    "تابع تطورات المشروع والخطوات القادمة": "Follow the project development and upcoming steps",

    // ---- Referral ----
    "نظام الإحالة": "Referral Program",
    "احصل على": "Earn",
    "لكل إحالة": "per referral",
    "رمز الإحالة الخاص بك": "Your Referral Code",
    "تم النسخ!": "Copied!",
    "تم نسخ رمز الإحالة": "Referral code copied",
    "انضم إلى": "Join",
    "واحصل على مكافآت! استخدم رمز الإحالة:": "and earn rewards! Use referral code:",
    "تم نسخ رابط المشاركة": "Share link copied",
    "الإحالات": "Referrals",
    "المكتسب": "Earned",
    "لديك رمز إحالة؟": "Have a referral code?",
    "تطبيق": "Apply",
    "تم تفعيل الإحالة": "Referral activated",
    "تم!": "Done!",

    // ---- MsRa Mining Card ----
    "تحقيق الهوية مطلوب": "Identity verification required",
    "يجب إكمال عملية تحقيق الهوية أولاً لتفعيل ميزة التعدين": "Complete identity verification first to activate mining",
    "انتقل لتحقيق الهوية": "Go to Identity Verification",
    "تسجيل عنوان Solana": "Register Solana Address",
    "عنوان محفظة Solana": "Solana Wallet Address",
    "ادخل عنوان محفظة Solana...": "Enter Solana wallet address...",
    "جاري التسجيل...": "Registering...",
    "تسجيل العنوان": "Register Address",
    "رصيد التعدين": "Mining Balance",
    "رصيد المحفظة": "Wallet Balance",
    "الإجمالي": "Total",
    "الرصيد الكلي": "Total Balance",
    "التعدين التالي": "Next Mining",
    "متاح الآن": "Available Now",
    "مؤشر التعدين EVM": "EVM Mining Indicator",
    "جاهز للتعدين": "Ready to Mine",
    "العنوان المسجل": "Registered Address",
    "Solana Address": "Solana Address",
    "الأصل والمصير": "Origin & Fate",

    // ---- Tasks Page ----
    "لا توجد مهام يومية متاحة حالياً": "No daily tasks available at the moment",
    "لا توجد مهام تطوير الشخصية متاحة حالياً": "No personality tasks available at the moment",
    "جاري تحميل الصفحات...": "Loading pages...",
    "لا توجد صفحات متاحة حالياً": "No pages available at the moment",
    "سيتم إضافة صفحات القرآن قريباً": "Quran pages will be added soon",
    "فتح الصفحة الأصلية": "Open Original Page",
    "ثانية متبقية": "seconds remaining",
    "تم إكمال القراءة": "Reading Completed",
    "تم إكمال القراءة!": "Reading Completed!",
    "جاري القراءة...": "Reading...",
    "ابدأ القراءة": "Start Reading",
    "الصفحة": "Page",
    "الجزء": "Part",
    "حدث خطأ أثناء إكمال القراءة": "Error completing reading",
    "تم إلغاء إكمال المهمة": "Task uncompleted",
    "حدث خطأ أثناء إلغاء إكمال المهمة": "Error uncompleting task",
    "تم إكمال المهمة!": "Task Completed!",
    "حدث خطأ أثناء إكمال المهمة": "Error completing task",

    // ---- CallOut Page ----
    "أرشيف الشخصيات المكرمة": "Honored Personalities Archive",
    "تايم لاين الشخصيات التي تم تكريمها على المنصة": "Timeline of personalities honored on the platform",
    "عالم": "Scientist",
    "فنان": "Artist",
    "مفكر": "Intellectual",
    "عامة (تصنيف)": "General",
    "تواصل": "Contact",

    // ---- StableCoin Page ----
    "العملة المستقرة المدعومة بالأصول المصرية": "Stablecoin backed by Egyptian assets",
    "الاستقرار والثبات": "Stability",
    "عملة مستقرة مدعومة بالأصول الحقيقية في مصر لضمان الثبات والأمان": "A stablecoin backed by real assets in Egypt for stability and security",
    "النمو المستدام": "Sustainable Growth",
    "نموذج اقتصادي مبتكر يدعم النمو المستدام للاقتصاد المحلي": "An innovative economic model supporting local sustainable growth",
    "ما هو MSR Stable Coin؟": "What is MSR Stable Coin?",
    "الميزات الرئيسية:": "Key Features:",
    "الورقة البيضاء (قريباً)": "Whitepaper (Coming Soon)",
    "احصل على MSR (قريباً)": "Get MSR (Coming Soon)",
    "نعمل على إطلاق MSR Stable Coin قريباً مع الشركاء المحليين": "Working on launching MSR Stable Coin soon with local partners",

    // ---- RWA Page ----
    "استثمر في الأصول الحقيقية المرموزة من مصر": "Invest in tokenized real-world assets from Egypt",
    "العقارات": "Real Estate",
    "استثمر في العقارات المصرية المرموزة": "Invest in tokenized Egyptian real estate",
    "التراث الثقافي": "Cultural Heritage",
    "أصول تراثية وثقافية مصرية مرموزة": "Tokenized Egyptian cultural heritage assets",
    "التجاري": "Commercial",
    "المشاريع التجارية والصناعية": "Commercial and industrial projects",
    "ما هو MSR-RWA؟": "What is MSR-RWA?",
    "كيف يعمل؟": "How does it work?",
    "الأمان والثقة": "Security & Trust",
    "استكشف الأصول (قريباً)": "Explore Assets (Coming Soon)",
    "ابدأ الاستثمار (قريباً)": "Start Investing (Coming Soon)",
    "المنصة قيد التطوير ويتم العمل على إطلاقها قريباً": "The platform is under development and launching soon",

    // ---- Documents Page ----
    "الخزانة الرقمية": "Digital Vault",
    "قم برفع وثائقك وصورك الشخصية بشكل آمن مع مصادقة ثنائية": "Upload your documents and personal photos securely with 2FA",
    "المصادقة الثنائية": "Two-Factor Authentication",
    "رمز التحقق": "Verification Code",
    "أدخل الرمز": "Enter the code",
    "تم التحقق ✓": "Verified ✓",
    "تحقق من الرمز": "Verify Code",
    "رفع الملفات": "Upload Files",
    "اختر الملف": "Select File",
    "رفع الملف": "Upload File",
    "معلومات مهمة": "Important Information",
    "نوع ملف غير مدعوم": "Unsupported file type",
    "حجم الملف كبير جداً": "File too large",
    "تم التحقق بنجاح": "Verified successfully",
    "يمكنك الآن رفع الملفات": "You can now upload files",
    "رمز غير صحيح": "Invalid code",
    "يرجى إدخال الرمز الصحيح": "Please enter the correct code",
    "يجب التحقق أولاً": "Verification required first",
    "تم رفع الملف بنجاح": "File uploaded successfully",
    "تم حفظ المستند بشكل آمن": "Document saved securely",
    "فشل رفع الملف": "File upload failed",

    // ---- Recharge Page ----
    "شحن نقاط XP": "Recharge XP Points",
    "اشحن نقاط XP باستخدام طرق الدفع المحلية المصرية": "Recharge XP using Egyptian local payment methods",
    "تفاصيل الشحن": "Recharge Details",
    "اختر المبلغ وطريقة الدفع": "Select amount and payment method",
    "المبلغ (جنيه مصري)": "Amount (EGP)",
    "أدخل المبلغ": "Enter amount",
    "طريقة الدفع": "Payment Method",
    "رقم المحفظة": "Wallet Number",
    "متابعة للدفع": "Proceed to Payment",
    "جاري المعالجة...": "Processing...",
    "الرجاء إدخال مبلغ صحيح": "Please enter a valid amount",
    "الرجاء اختيار طريقة دفع": "Please select a payment method",
    "الرجاء اختيار العملة": "Please select a currency",
    "الرجاء إدخال رقم المحفظة": "Please enter wallet number",
    "لا توجد طرق دفع متاحة": "No payment methods available",
    "نقاط الخبرة (شحن)": "Experience Points",
    "العملة الموحدة للمنصة": "Unified platform currency",
    "محددة تلقائياً": "Auto-selected",
    "نظام XP الموحد - بسيط وسريع!": "Unified XP System - Simple & Fast!",
    "كل شيء الآن بنقاط XP واحدة": "Everything is now with one XP currency",
    "اكسب XP": "Earn XP",
    "احصل على XP": "Get XP",
    "اشتري XP": "Buy XP",
    "الشحن": "Recharge",
    "ج.م": "EGP",
    "جاري التحقق من الدفع...": "Checking payment...",
    "تم الدفع بنجاح!": "Payment successful!",
    "تم إضافة الرصيد لحسابك": "Balance added to your account",
    "فشل الدفع": "Payment failed",
    "الرجاء المحاولة مرة أخرى": "Please try again",
    "سيتم إضافة الرصيد عند اكتمال المعاملة": "Balance will be added when transaction completes",
    "العودة للشحن": "Back to Recharge",
    "ملخص الطلب": "Order Summary",
    "ستحصل على": "You will get",
    "سعر الصرف": "Exchange Rate",
    "المعاملات الأخيرة": "Recent Transactions",
    "لا توجد معاملات سابقة": "No previous transactions",

    // ---- RoadmapDetail Page ----
    "لم يتم العثور على الصفحة المطلوبة": "Page not found",
    "العودة للرئيسية": "Back to Home",
    "المحتوى قيد الإعداد وسيتم نشره قريباً": "Content is being prepared and will be published soon",
    "الروابط": "Links",
    "الخدمات": "Services",
    "اختر الخدمات المتاحة": "Select available services",
    "متاح": "Available",

    // ---- ReelsCategories Page ----
    "أقسام الفيديوهات القصيرة": "Short Video Categories",
    "اختر القسم الذي تريد مشاهدة محتواه": "Choose the category you want to watch",
    "لا توجد أقسام متاحة حالياً": "No categories available currently",
    "سيتم إضافة أقسام جديدة قريباً": "New categories will be added soon",

    // ---- Anubis Page ----
    "محتويات الخزانة": "Vault Contents",
    "الملفات المحفوظة في خزانتك الرقمية": "Files stored in your digital vault",
    "لا توجد ملفات محفوظة حالياً": "No files stored currently",
    "ابدأ برفع ملفاتك بشكل آمن": "Start uploading your files securely",
    "رفع ملف جديد": "Upload New File",
    "قم برفع صورة أو مستند PDF (الحد الأقصى: 5 ميجابايت)": "Upload image or PDF (Max: 5MB)",
    "تأكيد الحذف": "Confirm Delete",
    "لا يمكن التراجع عن هذا الإجراء.": "This action cannot be undone.",
    "تم الحذف بنجاح": "Deleted successfully",
    "فشل الحذف": "Delete failed",
    "تم التحميل بنجاح": "Downloaded successfully",
    "فشل التحميل": "Download failed",
    "خطأ في جلب الملفات": "Error fetching files",

    // ---- LiveStreamsGallery Page ----
    "لا توجد بثوث نشطة حالياً": "No active streams currently",
    "تابع المؤثرين المفضلين لديك لتلقي إشعار عند بدء البث": "Follow your favorite influencers to get notified when they go live",
    "ابدأ بثك الخاص": "Start Your Own Stream",
    "البثوث المباشرة": "Live Streams",
    "بث نشط الآن": "active streams now",
    "ابدأ البث": "Start Streaming",
    "● مباشر": "● LIVE",
    "مشاهد": "viewers",
    "إعجاب": "likes",
    "مستخدم": "User",

    // ---- MyLiveStreams Page ----
    "بثوثي المباشرة": "My Live Streams",
    "بدء بث جديد": "Start New Stream",
    "يجب تسجيل الدخول لعرض بثوثك": "Sign in to view your streams",
    "لا يوجد بثوث حتى الآن": "No streams yet",
    "فشل تحميل البثوث": "Failed to load streams",
    "تم حذف البث": "Stream deleted",
    "فشل حذف البث": "Failed to delete stream",
    "مشاهدة البث": "Watch Stream",
    "إجمالي المشاهدات:": "Total Views:",
    "المشاهدون الحاليون:": "Current Viewers:",
    "الإعجابات:": "Likes:",
    "محذوف": "Deleted",
    "بدأ": "Started",
    "انتهى": "Ended",

    // ---- NotFound ----
    "الصفحة غير موجودة": "Page Not Found",
    "العودة للصفحة الرئيسية": "Return to Home",
  },

  ru: {
    // ---- Navigation ----
    "الرئيسية": "Главная",
    "المحفظة": "Кошелёк",
    "التعلم": "Обучение",
    "الاستبيانات": "Опросы",
    "البروفايل": "Профиль",
    "تسجيل الخروج": "Выйти",
    "تسجيل الدخول": "Войти",
    "انضم الآن": "Присоединиться",
    "التنقل الرئيسي": "Навигация",
    "الوصول المبكر": "Ранний доступ",
    "لوحة التحكم": "Панель управления",
    "رسالة جديدة": "Новое сообщение",
    "البث المباشر": "Прямой эфир",
    "التعدين": "Майнинг",
    "الهوية": "Удостоверение",
    "المستندات": "Документы",
    "التحديثات": "Обновления",
    "الدعم": "Поддержка",
    "العملة المستقرة": "Стейблкоин",
    "المهام اليومية": "Ежедневные задачи",
    "الريلز": "Рилсы",
    "خريطة الطريق": "Дорожная карта",
    "أنوبيس": "Анубис",
    "الاشتراك": "Подписка",

    // ---- Platform ----
    "منصة مصر الرقمية": "Цифровая платформа Египта",
    "منصة مصر": "Платформа Египта",
    "مصر": "MSR",

    // ---- Common UI ----
    "جاري التحميل...": "Загрузка...",
    "جاري التحقق من الصلاحيات...": "Проверка разрешений...",
    "جاري التحميل": "Загрузка",
    "يرجى تسجيل الدخول": "Пожалуйста, войдите",
    "للوصول إلى المحفظة": "для доступа к кошельку",
    "غير مصرح": "Нет доступа",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "У вас нет доступа к этой странице",
    "إعادة تحميل الصفحة": "Перезагрузить страницу",
    "المحاولة مرة أخرى": "Попробовать снова",
    "حدث خطأ غير متوقع": "Произошла непредвиденная ошибка",
    "عذراً، حدث خطأ في التطبيق. يرجى إعادة تحميل الصفحة.": "Извините, произошла ошибка. Пожалуйста, перезагрузите страницу.",
    "تفاصيل الخطأ": "Детали ошибки",
    "قريباً": "Скоро",

    // ---- Actions ----
    "حفظ": "Сохранить",
    "إلغاء": "Отмена",
    "تأكيد": "Подтвердить",
    "إرسال": "Отправить",
    "تحديث": "Обновить",
    "حذف": "Удалить",
    "إضافة": "Добавить",
    "تعديل": "Редактировать",
    "بحث": "Поиск",
    "عرض": "Просмотр",
    "رفع": "Загрузить",
    "تنزيل": "Скачать",
    "نسخ": "Копировать",
    "مشاركة": "Поделиться",
    "موافق": "OK",
    "رفض": "Отклонить",
    "قبول": "Принять",
    "تحويل": "Конвертировать",
    "سحب": "Вывести",

    // ---- Status ----
    "نشط": "Активен",
    "غير نشط": "Неактивен",
    "معلق": "Ожидание",
    "مكتمل": "Завершён",
    "مرفوض": "Отклонён",
    "موافق عليه": "Одобрен",
    "قيد المراجعة": "На рассмотрении",
    "منتهي": "Истёк",
    "متوقف": "Остановлен",
    "قيد التنفيذ": "Обработка",
    "فشل": "Ошибка",

    // ---- Auth ----
    "إنشاء حساب جديد": "Создать аккаунт",
    "الاسم الكامل": "Полное имя",
    "البريد الإلكتروني": "Email",
    "كلمة المرور": "Пароль",
    "رقم الهاتف": "Телефон",
    "الدخول بـ Google": "Войти через Google",
    "ليس لديك حساب؟": "Нет аккаунта?",
    "لديك حساب بالفعل؟": "Уже есть аккаунт?",
    "تم تسجيل الدخول بنجاح": "Вход выполнен",
    "مرحباً بك في منصة مصر": "Добро пожаловать на платформу Египта",
    "فشل تسجيل الدخول": "Ошибка входа",
    "تحقق من البيانات": "Проверьте данные",
    "تم إنشاء الحساب": "Аккаунт создан",
    "تحقق من بريدك لتفعيل الحساب": "Проверьте email для активации",
    "تعذر إنشاء الحساب": "Не удалось создать аккаунт",
    "إنشاء حساب": "Создать аккаунт",
    "حساب جديد": "Новый аккаунт",
    "جاري الدخول...": "Вход...",
    "دخول": "Войти",
    "جاري إنشاء الحساب...": "Создание аккаунта...",
    "أو": "или",
    "تسجيل الدخول بـ Google": "Войти через Google",
    "التسجيل بـ Google": "Регистрация через Google",
    "تسجيل الدخول عبر Telegram": "Войти через Telegram",
    "التسجيل عبر Telegram": "Регистрация через Telegram",
    "أو الدخول بالمحفظة": "или войти через кошелёк",
    "أو التسجيل بالمحفظة": "или зарегистрироваться через кошелёк",
    "فشل تسجيل الدخول بـ Google": "Ошибка входа через Google",
    "حدث خطأ، حاول مرة أخرى": "Произошла ошибка, попробуйте снова",
    "التسجيل عبر تيليجرام سيكون متاحاً قريباً": "Вход через Telegram скоро будет доступен",
    "تسجيل الدخول عبر تيليجرام سيكون متاحاً قريباً": "Вход через Telegram скоро будет доступен",
    "ربط محفظة Solana سيكون متاحاً قريباً": "Подключение Solana скоро",
    "ربط محفظة EVM سيكون متاحاً قريباً": "Подключение EVM скоро",
    "ربط محفظة TON سيكون متاحاً قريباً": "Подключение TON скоро",
    "ربط محفظة Solana": "Подключить Solana",
    "ربط محفظة EVM": "Подключить EVM",
    "ربط محفظة TON": "Подключить TON",

    // ---- Wallet ----
    "الرصيد": "Баланс",
    "استقبال": "Получить",
    "استلام": "Получить",
    "تاريخ المعاملات": "История операций",
    "المعاملة": "Операция",
    "المبلغ": "Сумма",
    "التاريخ": "Дата",
    "الحالة": "Статус",
    "عنوان المحفظة": "Адрес кошелька",
    "شحن المحفظة": "Пополнить кошелёк",
    "حوّل نقاطك إلى MS-RA": "Конвертируйте очки в MS-RA",
    "سحب إلى محفظة خارجية": "Вывести на внешний кошелёк",
    "المحافظ الخارجية": "Внешние кошельки",
    "المكافآت": "Награды",
    "قريباً ستتمكن من ربح مكافآت إضافية": "Скоро вы сможете получать дополнительные награды",
    "تبديل العملات": "Обмен токенов",
    "استلام العملات": "Получить токены",
    "إرسال العملات": "Отправить токены",
    "قم بتوصيل محفظة Solana أو EVM لعرض عنوان الاستلام": "Подключите Solana или EVM для получения адреса",
    "قم بتوصيل محفظة خارجية لإرسال العملات": "Подключите внешний кошелёк для отправки",
    "لا توجد معاملات": "Нет операций",
    "ستظهر معاملاتك هنا": "Ваши операции появятся здесь",
    "مركز التبادل": "Центр обмена",
    "ميزة الربح قادمة قريباً!": "Функция заработка скоро!",
    "إضافة عملات مخصصة قادمة قريباً": "Добавление токенов скоро",
    "اربح": "Заработать",
    "تبديل": "Обмен",

    // ---- Profile ----
    "تعديل البروفايل": "Редактировать профиль",
    "الاسم": "Имя",
    "البيو": "Описание",
    "المتابعون": "Подписчики",
    "المتابَعون": "Подписки",
    "الإنجازات": "Достижения",
    "حساب موثق": "Верифицирован",
    "تغيير الصورة": "Сменить фото",
    "البروفايل غير متوفر": "Профиль недоступен",
    "لم يتم العثور على بيانات البروفايل": "Данные профиля не найдены",
    "نظرة عامة": "Обзор",
    "عامة": "Обзор",
    "العائلة": "Семья",
    "عائلة": "Семья",
    "تحرير": "Ред.",
    "النشاط": "Активность",
    "نشاط": "Актив.",
    "الإعدادات": "Настройки",
    "إعدادات": "Настройки",
    "معلومات الملف الشخصي": "Информация профиля",
    "غير محدد": "Не указано",
    "تاريخ الانضمام": "Дата регистрации",
    "اللغة المفضلة": "Язык",
    "العربية": "Арабский",
    "روابط التواصل": "Соцсети",
    "الموقع الشخصي": "Сайт",
    "لا توجد روابط متاحة": "Нет ссылок",
    "البادجات": "Значки",
    "نقاط الخبرة": "Очки опыта",
    "إجمالي النقاط": "Всего очков",
    "رصيد XP": "Баланс XP",
    "المحافظ المربوطة": "Подключённые кошельки",
    "لا توجد محافظ مربوطة": "Кошельки не подключены",
    "الاستبيانات المكتملة": "Пройденные опросы",
    "لم يتم إكمال أي استبيان بعد": "Опросы ещё не пройдены",
    "سجل النشاط": "Журнал активности",
    "تتبع نشاطاتك الأخيرة على المنصة": "Отслеживайте свою активность",
    "لا توجد أنشطة مسجلة حتى الآن": "Нет записей активности",
    "إعدادات الحساب": "Настройки аккаунта",
    "إدارة إعدادات الخصوصية والأمان": "Управление конфиденциальностью и безопасностью",
    "إعدادات الخصوصية": "Настройки приватности",
    "التحكم في من يمكنه رؤية معلوماتك": "Управление видимостью данных",
    "الأمان": "Безопасность",
    "تغيير كلمة المرور والمصادقة الثنائية": "Пароль и двухфакторная аутентификация",
    "الإشعارات": "Уведомления",
    "إدارة تفضيلات الإشعارات": "Настройки уведомлений",
    "المتابعات": "Подписки",
    "متابع": "Подписчиков",
    "يتابع": "Подписок",

    // ---- Mining ----
    "بدء التعدين": "Начать майнинг",
    "إيقاف التعدين": "Остановить майнинг",
    "معدل التعدين": "Скорость майнинга",
    "إجمالي التعدين": "Всего добыто",
    "مستوى التعدين": "Уровень майнинга",
    "لوحة التعدين": "Панель майнинга",
    "تتبع تقدم التعدين وقوة حسابك": "Отслеживайте прогресс майнинга и силу аккаунта",
    "تم التحديث": "Обновлено",
    "فشل في تحديث التعدين": "Ошибка обновления майнинга",
    "تم إيقاف التعدين": "Майнинг остановлен",
    "التعدين متوقف الآن": "Майнинг остановлен",
    "تم تشغيل التعدين": "Майнинг запущен",
    "التعدين يعمل الآن": "Майнинг активен",
    "فشل في تغيير حالة التعدين": "Ошибка изменения статуса",
    "جاري تحميل بيانات التعدين...": "Загрузка данных майнинга...",
    "إعادة المحاولة": "Повторить",
    "قوة الحساب": "Сила аккаунта",
    "نقطة": "Очков",
    "المستوى الحالي": "Текущий уровень",
    "حالة التعدين": "Статус майнинга",
    "التعدين منذ:": "Майнинг с:",
    "جاري التحديث...": "Обновление...",
    "تحديث الآن": "Обновить",
    "التعدين الحالي": "Текущий майнинг",
    "سيتم إضافتها عند التحديث التالي": "Будет добавлено при обновлении",
    "تقدم المستوى": "Прогресс уровня",
    "الحد الأقصى": "Максимум",
    "القوة المطلوبة:": "Необходимая сила:",
    "المستوى التالي": "Следующий уровень",
    "التعدين خلال 24 ساعة": "Майнинг за 24ч",
    "لا توجد بيانات تعدين خلال الـ 24 ساعة الماضية": "Нет данных майнинга за 24 часа",
    "مستويات التعدين": "Уровни майнинга",
    "المستوى": "Уровень",
    "المعدل": "Скорость",
    "القوة": "Сила",
    "معدل التعدين:": "Скорость:",
    "تكلفة الترقية:": "Стоимость улучшения:",
    "بدء": "Старт",
    "إيقاف": "Стоп",

    // ---- Support ----
    "إرسال رسالة": "Отправить сообщение",
    "موضوع الرسالة": "Тема",
    "نص الرسالة": "Сообщение",
    "الرسائل المرسلة": "Отправленные",
    "رد الدعم": "Ответ поддержки",
    "إرسال الرسالة": "Отправить",
    "الموضوع": "Тема",
    "الأولوية": "Приоритет",
    "الرسالة": "Сообщение",
    "منخفض": "Низкий",
    "عادي": "Обычный",
    "عالي": "Высокий",
    "عاجل": "Срочный",
    "تم إرسال الرسالة": "Сообщение отправлено",
    "سيتم الرد عليك في أقرب وقت ممكن": "Мы ответим как можно скорее",
    "جاري الإرسال...": "Отправка...",
    "رسائلك السابقة": "Предыдущие сообщения",
    "لا توجد رسائل سابقة": "Нет предыдущих сообщений",
    "رسالتك:": "Ваше сообщение:",
    "رد الإدارة:": "Ответ админа:",
    "قيد الانتظار": "Ожидание",
    "قيد المعالجة": "Обработка",
    "تم الحل": "Решено",
    "مغلق": "Закрыто",

    // ---- Learning ----
    "الدروس": "Уроки",
    "المقالات": "Статьи",
    "الفيديوهات": "Видео",
    "اختبار": "Тест",
    "الدرجة": "Балл",
    "اجتاز": "Сдал",
    "رسب": "Не сдал",
    "المنصة التفاعلية": "Интерактивная платформа",
    "تعلم، شارك، وتفاعل مع مجتمع المتداولين والمستثمرين في العملات الرقمية": "Учитесь, делитесь и общайтесь с сообществом крипто-трейдеров",
    "شارك محتوى تعليمي": "Поделиться обучающим контентом",
    "رسالة المنصة": "Сообщение платформы",
    "السابقة": "Предыдущее",
    "التالية": "Следующее",
    "مالي": "Финансы",
    "عام": "Общее",
    "ديني": "Религия",
    "إنشاء منشور جديد": "Создать новый пост",
    "إنشاء منشور تعليمي": "Создать обучающий пост",
    "عنوان المنشور": "Заголовок поста",
    "محتوى المنشور": "Содержание поста",
    "نوع المحتوى": "Тип контента",
    "نص": "Текст",
    "صورة": "Изображение",
    "فيديو": "Видео",
    "صوت": "Аудио",
    "مختلط": "Смешанный",
    
    "مستوى الصعوبة": "Уровень сложности",
    "مبتدئ": "Начинающий",
    "متوسط": "Средний",
    "متقدم": "Продвинутый",
    "القسم": "Раздел",
    "العلامات (مفصولة بفواصل)": "Теги (через запятую)",
    "نشر المحتوى": "Опубликовать",
    "مؤلف مجهول": "Неизвестный автор",
    "ثنائي اللغة": "Двуязычный",
    "مجهول": "Аноним",
    "اكتب تعليقاً...": "Напишите комментарий...",
    "حدث خطأ في جلب المنشورات": "Ошибка загрузки постов",
    "يرجى إدخال عنوان المنشور": "Введите заголовок поста",
    "تم إنشاء المنشور": "Пост создан",
    "تم إنشاء المنشور بنجاح": "Пост успешно создан",
    "حدث خطأ في إنشاء المنشور": "Ошибка создания поста",

    // ---- Surveys ----
    "الاستبيان": "Опрос",
    "الأسئلة": "Вопросы",
    "الإجابات": "Ответы",
    "إرسال الاستبيان": "Отправить опрос",
    "لم يكتمل": "Не завершён",

    // ---- Early Access ----
    "طلب الوصول المبكر": "Запрос раннего доступа",
    "في انتظار الموافقة": "Ожидание одобрения",
    "تم قبولك": "Вы приняты",
    "لم تتم الموافقة بعد": "Ещё не одобрено",
    "شكراً لتسجيلك في منصة مصر": "Спасибо за регистрацию на платформе Египта",
    "نحن نعمل حالياً على الإطلاق الرسمي للمنصة. سيتم إشعارك عبر البريد الإلكتروني فور إتاحة الوصول الكامل.": "Мы работаем над официальным запуском. Вы получите уведомление по email, когда полный доступ будет открыт.",
    "نقدر صبرك وثقتك بنا": "Благодарим за терпение и доверие",

    // ---- Live Stream ----
    "بث مباشر": "Прямой эфир",
    "شاهد البث": "Смотреть",
    "بدء البث": "Начать трансляцию",
    "إنهاء البث": "Завершить",
    "المشاهدون": "Зрители",
    "تعليق": "Комментарий",
    "التعليقات": "Комментарии",

    // ---- Daily Tasks ----
    "المهام | Tasks": "Задачи",
    "أكمل مهامك اليومية لتحصل على النقاط وتبني سلسلة حضورك المتتالي": "Выполняйте задания для получения очков и увеличения серии",
    "السلسلة:": "Серия:",
    "أطول سلسلة:": "Лучшая серия:",
    "الجلسات:": "Сессии:",
    "مهامك اليومية": "Ваши ежедневные задачи",
    "قرآن": "Коран",
    "شخصية": "Личность",
    "يومية": "Ежедневные",
    "عجلة الحظ": "Колесо удачи",
    "لا توجد مهام يومية متاحة حالياً": "Нет ежедневных задач",
    "لا توجد مهام تطوير الشخصية متاحة حالياً": "Нет задач по развитию личности",
    "جاري تحميل الصفحات...": "Загрузка страниц...",
    "لا توجد صفحات متاحة حالياً": "Нет доступных страниц",
    "سيتم إضافة صفحات القرآن قريباً": "Страницы Корана будут добавлены скоро",
    "فتح الصفحة الأصلية": "Открыть оригинал",
    "ثانية متبقية": "сек. осталось",
    "تم إكمال القراءة": "Чтение завершено",
    "تم إكمال القراءة!": "Чтение завершено!",
    "جاري القراءة...": "Чтение...",
    "ابدأ القراءة": "Начать чтение",
    "الصفحة": "Страница",
    "الجزء": "Часть",
    "حدث خطأ أثناء إكمال القراءة": "Ошибка при завершении чтения",
    "تم إلغاء إكمال المهمة": "Задача отменена",
    "حدث خطأ أثناء إلغاء إكمال المهمة": "Ошибка при отмене задачи",
    "تم إكمال المهمة!": "Задача выполнена!",
    "حدث خطأ أثناء إكمال المهمة": "Ошибка при выполнении задачи",

    // ---- Admin ----
    "إدارة المستخدمين": "Управление пользователями",
    "إدارة الوصول المبكر": "Ранний доступ",
    "رسائل الدعم": "Сообщения поддержки",
    "إدارة الحسابات المعتمدة": "Верифицированные аккаунты",
    "إدارة الهوية": "Управление ID",
    "إدارة الاستبيانات": "Управление опросами",
    "إدارة التعلم": "Управление обучением",
    "إدارة محتوى التطبيق": "Контент приложения",
    "إدارة التحديثات": "Управление обновлениями",
    "إدارة مستويات التعدين": "Уровни майнинга",
    "إدارة مواقع المتعاونين": "Локации партнёров",
    "إدارة الإعلانات": "Объявления",
    "إدارة البادجات": "Значки",
    "إدارة كارت أنوبيس": "Карточка Анубис",
    "إدارة الاستدعاء النشط": "Активный вызов",
    "قائمة الاستدعاء الشرفية": "Почётный список",
    "إحصائيات التفاعل": "Статистика вовлечённости",
    "المهام اليومية (إدارة)": "Ежедневные задачи",
    "إدارة صفحات القرآن": "Страницы Корана",
    "إدارة الوسائط": "Медиа",
    "مهام تطوير الشخصية": "Задачи личности",
    "إدارة مقدمات المهام": "Введения задач",
    "إدارة أقسام الريلز": "Категории рилсов",
    "إدارة كارت الاستدعاء": "Карточка вызова",
    "إعدادات التحويل": "Настройки конвертации",
    "إدارة كروت الرودماب": "Карточки дорожной карты",
    "إدارة بطاقات الصفحة الرئيسية": "Карточки главной",
    "إعدادات البروفايل": "Настройки профиля",
    "إدارة طلبات البث المباشر": "Заявки на трансляцию",
    "إدارة العملات الداخلية": "Внутренние токены",
    "إدارة مجمع السيولة": "Пул ликвидности",
    "إدارة عجلة الحظ": "Колесо удачи",
    "إدارة طلبات العائلة": "Заявки семьи",
    "إدارة رسالة المنصة": "Сообщение платформы",

    // ---- Errors ----
    "خطأ": "Ошибка",
    "حدث خطأ": "Произошла ошибка",
    "فشل في التحميل": "Ошибка загрузки",
    "فشل في الحفظ": "Ошибка сохранения",
    "فشل في الإرسال": "Ошибка отправки",
    "فشل في تحميل البروفايل": "Ошибка загрузки профиля",

    // ---- Success ----
    "تم بنجاح": "Готово",
    "تم الحفظ": "Сохранено",
    "تم الإرسال": "Отправлено",

    // ---- Misc ----
    "الدفع بـ Pi": "Оплата Pi",
    "إعادة الشحن": "Пополнение",
    "الإعلانات": "Объявления",
    "التوثيق": "Верификация",
    "الخصوصية": "Конфиденциальность",
    "سياسة الخصوصية": "Политика конфиденциальности",
    "استبيان": "Опрос",
    "محفظة العملات الرقمية": "Цифровой крипто-кошелёк",
    "منصة بسيطة للعملات الرقمية مع محفظة آمنة وتوثيق الهوية": "Простая крипто-платформа с безопасным кошельком и верификацией личности",

    // ---- CallOut Page ----
    "أرشيف الشخصيات المكرمة": "Архив почётных личностей",
    "تايم لاين الشخصيات التي تم تكريمها على المنصة": "Хронология почётных личностей на платформе",
    "عالم": "Учёный",
    "فنان": "Артист",
    "مفكر": "Мыслитель",
    "عامة (تصنيف)": "Общее",
    "تواصل": "Связаться",

    // ---- StableCoin Page ----
    "العملة المستقرة المدعومة بالأصول المصرية": "Стейблкоин, обеспеченный египетскими активами",
    "الاستقرار والثبات": "Стабильность",
    "عملة مستقرة مدعومة بالأصول الحقيقية في مصر لضمان الثبات والأمان": "Стейблкоин, обеспеченный реальными активами Египта",
    "النمو المستدام": "Устойчивый рост",
    "نموذج اقتصادي مبتكر يدعم النمو المستدام للاقتصاد المحلي": "Инновационная экономическая модель устойчивого роста",
    "ما هو MSR Stable Coin؟": "Что такое MSR Stable Coin?",
    "الميزات الرئيسية:": "Ключевые особенности:",
    "الورقة البيضاء (قريباً)": "Whitepaper (Скоро)",
    "احصل على MSR (قريباً)": "Получить MSR (Скоро)",
    "نعمل على إطلاق MSR Stable Coin قريباً مع الشركاء المحليين": "Скоро запускаем MSR Stable Coin с местными партнёрами",

    // ---- RWA Page ----
    "استثمر في الأصول الحقيقية المرموزة من مصر": "Инвестируйте в токенизированные реальные активы Египта",
    "العقارات": "Недвижимость",
    "استثمر في العقارات المصرية المرموزة": "Инвестируйте в токенизированную египетскую недвижимость",
    "التراث الثقافي": "Культурное наследие",
    "أصول تراثية وثقافية مصرية مرموزة": "Токенизированные активы культурного наследия Египта",
    "التجاري": "Коммерческое",
    "المشاريع التجارية والصناعية": "Коммерческие и промышленные проекты",
    "ما هو MSR-RWA؟": "Что такое MSR-RWA?",
    "كيف يعمل؟": "Как это работает?",
    "الأمان والثقة": "Безопасность и доверие",
    "استكشف الأصول (قريباً)": "Исследовать активы (Скоро)",
    "ابدأ الاستثمار (قريباً)": "Начать инвестировать (Скоро)",
    "المنصة قيد التطوير ويتم العمل على إطلاقها قريباً": "Платформа в разработке, скоро запуск",

    // ---- Documents Page ----
    "الخزانة الرقمية": "Цифровое хранилище",
    "قم برفع وثائقك وصورك الشخصية بشكل آمن مع مصادقة ثنائية": "Загружайте документы и фото с двухфакторной аутентификацией",
    "المصادقة الثنائية": "Двухфакторная аутентификация",
    "رمز التحقق": "Код подтверждения",
    "أدخل الرمز": "Введите код",
    "تم التحقق ✓": "Подтверждено ✓",
    "تحقق من الرمز": "Проверить код",
    "رفع الملفات": "Загрузка файлов",
    "اختر الملف": "Выберите файл",
    "رفع الملف": "Загрузить файл",
    "معلومات مهمة": "Важная информация",
    "نوع ملف غير مدعوم": "Неподдерживаемый тип файла",
    "حجم الملف كبير جداً": "Файл слишком большой",
    "تم التحقق بنجاح": "Успешно подтверждено",
    "يمكنك الآن رفع الملفات": "Теперь можно загружать файлы",
    "رمز غير صحيح": "Неверный код",
    "يرجى إدخال الرمز الصحيح": "Введите правильный код",
    "يجب التحقق أولاً": "Сначала пройдите проверку",
    "تم رفع الملف بنجاح": "Файл загружен успешно",
    "تم حفظ المستند بشكل آمن": "Документ сохранён безопасно",
    "فشل رفع الملف": "Ошибка загрузки файла",

    // ---- Recharge Page ----
    "شحن نقاط XP": "Пополнить XP",
    "اشحن نقاط XP باستخدام طرق الدفع المحلية المصرية": "Пополните XP египетскими способами оплаты",
    "تفاصيل الشحن": "Детали пополнения",
    "اختر المبلغ وطريقة الدفع": "Выберите сумму и способ оплаты",
    "المبلغ (جنيه مصري)": "Сумма (EGP)",
    "أدخل المبلغ": "Введите сумму",
    "طريقة الدفع": "Способ оплаты",
    "رقم المحفظة": "Номер кошелька",
    "متابعة للدفع": "Перейти к оплате",
    "جاري المعالجة...": "Обработка...",
    "الرجاء إدخال مبلغ صحيح": "Введите корректную сумму",
    "الرجاء اختيار طريقة دفع": "Выберите способ оплаты",
    "الرجاء اختيار العملة": "Выберите валюту",
    "الرجاء إدخال رقم المحفظة": "Введите номер кошелька",
    "لا توجد طرق دفع متاحة": "Нет доступных способов оплаты",
    "نقاط الخبرة (شحن)": "Очки опыта",
    "العملة الموحدة للمنصة": "Единая валюта платформы",
    "محددة تلقائياً": "Авто-выбор",
    "نظام XP الموحد - بسيط وسريع!": "Единая система XP — просто и быстро!",
    "كل شيء الآن بنقاط XP واحدة": "Всё теперь в единых очках XP",
    "اكسب XP": "Зарабатывайте XP",
    "احصل على XP": "Получайте XP",
    "اشتري XP": "Покупайте XP",
    "الشحن": "Пополнение",
    "ج.م": "EGP",
    "جاري التحقق من الدفع...": "Проверка оплаты...",
    "تم الدفع بنجاح!": "Оплата успешна!",
    "تم إضافة الرصيد لحسابك": "Баланс зачислен",
    "فشل الدفع": "Ошибка оплаты",
    "الرجاء المحاولة مرة أخرى": "Попробуйте снова",
    "سيتم إضافة الرصيد عند اكتمال المعاملة": "Баланс зачислится после завершения",
    "العودة للشحن": "Назад к пополнению",
    "ملخص الطلب": "Итог заказа",
    "ستحصل على": "Вы получите",
    "سعر الصرف": "Курс обмена",
    "المعاملات الأخيرة": "Последние транзакции",
    "لا توجد معاملات سابقة": "Нет предыдущих транзакций",

    // ---- RoadmapDetail Page ----
    "لم يتم العثور على الصفحة المطلوبة": "Страница не найдена",
    "العودة للرئيسية": "На главную",
    "المحتوى قيد الإعداد وسيتم نشره قريباً": "Контент готовится и будет опубликован скоро",
    "الروابط": "Ссылки",
    "الخدمات": "Услуги",
    "اختر الخدمات المتاحة": "Выберите доступные услуги",
    "متاح": "Доступно",

    // ---- Identity Verification (ru) ----
    "توثيق الهوية": "Верификация личности",
    "عملية التحقق من الهوية (KYC) تضمن أمان حسابك والامتثال للمعايير المطلوبة. يرجى تقديم بيانات دقيقة ومطابقة للوثائق الرسمية.": "Процесс верификации (KYC) обеспечивает безопасность вашего аккаунта. Пожалуйста, предоставьте точные данные, совпадающие с официальными документами.",
    "تحذير مهم": "Важное предупреждение",
    "يرجى تحري الدقة الكاملة ومطابقة الواقع في جميع المعلومات المقدمة.": "Убедитесь в полной точности предоставленной информации.",
    "حالة التحقق الحالية": "Текущий статус верификации",
    "تم التحقق": "Подтверждено",
    "مسودة": "Черновик",
    "ملاحظات": "Примечания",
    "تاريخ الطلب": "Дата заявки",
    "آخر تحديث": "Последнее обновление",
    "المعلومات الشخصية": "Личные данные",
    "أدخل معلوماتك الشخصية الصحيحة والمطابقة للوثائق الرسمية": "Введите точные данные, совпадающие с документами",
    "تاريخ الميلاد": "Дата рождения",
    "الجنسية": "Гражданство",
    "العنوان الكامل": "Полный адрес",
    "حفظ والمتابعة": "Сохранить и продолжить",
    "جاري الحفظ...": "Сохранение...",
    "بيانات ناقصة": "Неполные данные",
    "يرجى ملء جميع الحقول المطلوبة": "Заполните все обязательные поля",
    "تم حفظ البيانات": "Данные сохранены",
    "تم حفظ معلوماتك الشخصية بنجاح": "Ваши личные данные сохранены",
    "خطأ في الحفظ": "Ошибка сохранения",
    "حدث خطأ أثناء حفظ البيانات": "Ошибка при сохранении данных",
    "رفع الوثائق": "Загрузка документов",
    "اختر نوع الوثيقة وأدخل رقمها": "Выберите тип документа и введите номер",
    "نوع الوثيقة": "Тип документа",
    "اختر نوع الوثيقة": "Выберите тип документа",
    "رقم الوثيقة": "Номер документа",
    "أدخل رقم الوثيقة": "Введите номер документа",
    "الهوية الوطنية": "Удостоверение личности",
    "جواز السفر": "Паспорт",
    "رخصة القيادة": "Водительское удостоверение",
    "الإقامة": "Вид на жительство",
    "صورة الوثيقة - الوجه الأمامي": "Фото документа — лицевая сторона",
    "صورة الوثيقة - الوجه الخلفي (اختياري)": "Фото документа — обратная сторона (необязательно)",
    "صورة شخصية مع حمل الوثيقة": "Селфи с документом",
    "اضغط لرفع الصورة": "Нажмите для загрузки фото",
    "فتح الكاميرا": "Открыть камеру",
    "رفع صورة": "Загрузить фото",
    "إزالة الصورة": "Удалить фото",
    "اختر طريقة إضافة الصورة": "Выберите способ добавления фото",
    "جاري الرفع...": "Загрузка...",
    "متطلبات الوثائق:": "Требования к документам:",
    "السابق": "Назад",
    "إرسال للمراجعة": "Отправить на проверку",
    "الوثائق مطلوبة": "Документы обязательны",
    "يرجى رفع صورة الوثيقة والصورة الشخصية": "Загрузите фото документа и селфи",
    "يرجى اختيار نوع الوثيقة وإدخال رقمها": "Выберите тип документа и введите номер",
    "تم إرسال الطلب": "Заявка отправлена",
    "تم إرسال طلب التحقق من الهوية للمراجعة": "Заявка на верификацию отправлена на проверку",
    "خطأ في الإرسال": "Ошибка отправки",
    "حدث خطأ أثناء رفع الوثائق": "Ошибка при загрузке документов",
    "مراجعة الطلب": "Проверка заявки",
    "تم استلام طلبك وهو قيد المراجعة من قبل فريقنا": "Ваша заявка получена и проверяется",
    "طلبك قيد المراجعة": "Ваша заявка на рассмотрении",
    "يستغرق التحقق من الهوية عادة من 1-3 أيام عمل. سنقوم بإشعارك فور اكتمال المراجعة.": "Верификация обычно занимает 1-3 рабочих дня. Вы получите уведомление по завершении.",
    "ملخص الطلب:": "Итог заявки:",
    "ماذا بعد؟": "Что дальше?",
    "سبب الرفض:": "Причина отказа:",
    "إعادة تقديم الطلب": "Повторная подача",
    "تم التحقق في:": "Подтверждено:",

    // ---- Updates Page (ru) ----
    "آخر التحديثات": "Последние обновления",
    "تابع آخر الأخبار والتحديثات في منصة Crypto-MSR": "Следите за новостями и обновлениями Crypto-MSR",
    "تحديث جديد": "Новое обновление",
    "جديد": "Новое",
    "اقرأ المزيد": "Подробнее",
    "لا توجد تحديثات حالياً": "Обновлений пока нет",
    "سيتم إضافة التحديثات هنا عند توفرها": "Обновления появятся здесь",
    "المزيد من التحديثات قريباً": "Скоро будут ещё обновления",
    "نعمل باستمرار على تطوير المنصة وإضافة ميزات جديدة": "Мы постоянно развиваем платформу и добавляем новые функции",

    // ---- Surveys Page (ru) ----
    "الاستبيانات (Surveys)": "Опросы",
    "شاركنا آراءك وساهم في تحسين تجربة المستخدمين على منصتنا.": "Поделитесь мнением и помогите улучшить платформу.",
    "يجب تسجيل الدخول للمشاركة في الاستبيانات": "Войдите, чтобы участвовать в опросах",
    "لا توجد استبيانات نشطة حالياً.": "Нет активных опросов.",
    "أسئلة": "вопросов",
    "عدة أسئلة": "Несколько вопросов",

    // ---- Home Cards (ru) ----
    "أنوبيس - حامي الأسرار": "Анубис — Хранитель тайн",
    "اضغط لاكتشاف أسرار أنوبيس القديمة": "Нажмите, чтобы открыть древние тайны Анубиса",
    "للأعضاء المعتمدين والمؤثرين": "Для верифицированных участников и инфлюенсеров",
    "يتطلب دعوة أو موافقة إدارية": "Требуется приглашение или одобрение",
    "شاهد مجموعة مختارة من الفيديوهات التعليمية القصيرة": "Смотрите подборку коротких обучающих видео",
    "إجمالي التعدين العالمي": "Глобальный прогресс майнинга",
    "من": "из",
    "معدّن نشط": "активных майнеров",
    "تابع تطورات المشروع والخطوات القادمة": "Следите за развитием проекта",

    // ---- Referral (ru) ----
    "نظام الإحالة": "Реферальная программа",
    "احصل على": "Получите",
    "لكل إحالة": "за приглашение",
    "رمز الإحالة الخاص بك": "Ваш реферальный код",
    "تم النسخ!": "Скопировано!",
    "تم نسخ رمز الإحالة": "Реферальный код скопирован",
    "الإحالات": "Приглашения",
    "المكتسب": "Заработано",
    "لديك رمز إحالة؟": "Есть реферальный код?",
    "تطبيق": "Применить",
    "تم تفعيل الإحالة": "Реферал активирован",
    "تم!": "Готово!",

    // ---- LiveStream Page (ru) ----
    "منصة البث المباشر": "Платформа прямых трансляций",
    "للأعضاء المعتمدين والمؤثرين والمشاهير": "Для верифицированных участников, блогеров и знаменитостей",
    "شاهد البثوث المباشرة للآخرين": "Смотрите трансляции других",
    "حالة الطلب": "Статус заявки",
    "معتمد": "Одобрено",
    "تاريخ التقديم": "Дата подачи",
    "تاريخ المراجعة": "Дата проверки",
    "سبب الرفض": "Причина отказа",
    "تم اعتماد حسابك - ابدأ البث الآن!": "Ваш аккаунт одобрён — начните трансляцию!",
    "يمكنك الآن بدء البث المباشر من التطبيق مباشرة": "Теперь вы можете начать трансляцию прямо из приложения",
    "تقديم طلب الاعتماد": "Подать заявку на одобрение",
    "يرجى ملء البيانات التالية للحصول على موافقة الإدارة": "Заполните данные для получения одобрения",
    "الاسم الكامل *": "Полное имя *",
    "البريد الإلكتروني *": "Email *",
    "روابط وسائل التواصل الاجتماعي": "Ссылки на соцсети",
    "إضافة رابط": "Добавить ссылку",
    "عدد المتابعين": "Количество подписчиков",
    "نبذة عنك ولماذا تريد البث المباشر *": "О себе и почему хотите вести трансляцию *",
    "يجب تسجيل الدخول أولاً": "Сначала войдите в аккаунт",
    "تم إرسال الطلب بنجاح": "Заявка отправлена успешно",
    "سيتم مراجعة طلبك من قبل الإدارة قريباً": "Ваша заявка будет рассмотрена в ближайшее время",
    "فشل في إرسال الطلب": "Ошибка отправки заявки",
    "إرسال الطلب": "Отправить заявку",
    "يجب تسجيل الدخول للوصول إلى منصة البث المباشر": "Войдите для доступа к платформе трансляций",

    // ---- MsRa Mining Card (ru) ----
    "تحقيق الهوية مطلوب": "Требуется верификация",
    "يجب إكمال عملية تحقيق الهوية أولاً لتفعيل ميزة التعدين": "Пройдите верификацию для активации майнинга",
    "انتقل لتحقيق الهوية": "Перейти к верификации",
    "رصيد التعدين": "Баланс майнинга",
    "رصيد المحفظة": "Баланс кошелька",
    "الإجمالي": "Итого",
    "الرصيد الكلي": "Общий баланс",

    // ---- ReelsCategories Page ----
    "أقسام الفيديوهات القصيرة": "Категории коротких видео",
    "اختر القسم الذي تريد مشاهدة محتواه": "Выберите категорию для просмотра",
    "لا توجد أقسام متاحة حالياً": "Нет доступных категорий",
    "سيتم إضافة أقسام جديدة قريباً": "Новые категории скоро появятся",

    // ---- Anubis Page ----
    "محتويات الخزانة": "Содержимое хранилища",
    "الملفات المحفوظة في خزانتك الرقمية": "Файлы в вашем цифровом хранилище",
    "لا توجد ملفات محفوظة حالياً": "Нет сохранённых файлов",
    "ابدأ برفع ملفاتك بشكل آمن": "Начните загружать файлы безопасно",
    "رفع ملف جديد": "Загрузить новый файл",
    "قم برفع صورة أو مستند PDF (الحد الأقصى: 5 ميجابايت)": "Загрузите фото или PDF (макс: 5МБ)",
    "تأكيد الحذف": "Подтвердить удаление",
    "لا يمكن التراجع عن هذا الإجراء.": "Это действие нельзя отменить.",
    "تم الحذف بنجاح": "Успешно удалено",
    "فشل الحذف": "Ошибка удаления",
    "تم التحميل بنجاح": "Успешно скачано",
    "فشل التحميل": "Ошибка скачивания",
    "خطأ في جلب الملفات": "Ошибка получения файлов",

    // ---- LiveStreamsGallery Page ----
    "لا توجد بثوث نشطة حالياً": "Нет активных трансляций",
    "تابع المؤثرين المفضلين لديك لتلقي إشعار عند بدء البث": "Подпишитесь на любимых блогеров, чтобы получать уведомления",
    "ابدأ بثك الخاص": "Начните свою трансляцию",
    "البثوث المباشرة": "Прямые трансляции",
    "بث نشط الآن": "активных трансляций",
    "ابدأ البث": "Начать трансляцию",
    "● مباشر": "● LIVE",
    "مشاهد": "зрителей",
    "إعجاب": "лайков",
    "مستخدم": "Пользователь",

    // ---- MyLiveStreams Page ----
    "بثوثي المباشرة": "Мои трансляции",
    "بدء بث جديد": "Новая трансляция",
    "يجب تسجيل الدخول لعرض بثوثك": "Войдите, чтобы видеть свои трансляции",
    "لا يوجد بثوث حتى الآن": "Трансляций пока нет",
    "فشل تحميل البثوث": "Ошибка загрузки трансляций",
    "تم حذف البث": "Трансляция удалена",
    "فشل حذف البث": "Ошибка удаления трансляции",
    "مشاهدة البث": "Смотреть",
    "إجمالي المشاهدات:": "Всего просмотров:",
    "المشاهدون الحاليون:": "Текущие зрители:",
    "الإعجابات:": "Лайки:",
    "محذوف": "Удалён",
    "بدأ": "Начало",
    "انتهى": "Окончание",

    // ---- NotFound ----
    "الصفحة غير موجودة": "Страница не найдена",
    "العودة للصفحة الرئيسية": "Вернуться на главную",

    // ---- Daily Tasks Intro (long texts) ----
    "مرحباً بك في المهام اليومية": "Добро пожаловать в ежедневные задачи",
    [`الانتظام في آداء المهام ،،، و تنظيم الوقت ...هو تدريب علي الأنضباط و المثابرة
لذلك الصدق و النزاهة هم لمصلحتك ...اما الغش و الخداع يجعلك متأخرا ليس أكثر..
.لانه بعد بضع اسابيع ستري تأثير الصدق والالتزام علي كل جوانب حياتك`]: "Регулярное выполнение задач и управление временем — это тренировка дисциплины и настойчивости. Честность и порядочность служат вашему развитию, а обман лишь задерживает вас. Через несколько недель вы увидите влияние честности и приверженности на все стороны вашей жизни.",
    "المهام العامة": "Общие задачи",
    [`تسجيل حضورك بشكل يومي في توقيت محدد... يعزز انتمائك للمنصة... و يعطيك مؤشر علي قدرتك علي الالتزام  و المثابرة و الانضباط... وهو كل ما يتطلبه النجاح في كل مكان و في كل الظروف و يفتح الطريق لمعرفة امكانياتك بشكل افضل... انشاءك قائمة المهام اليومية الخاصة بك و تثبيت مواقيت لانجازها... يعطي مؤشر ممتاز،. سواء نجحت في الالتزام بها ام لا.... فهذا ما يفعله كل رواد الاعمال و الناجحين حول العالم`]: "Ежедневная регистрация в определённое время укрепляет вашу связь с платформой и показывает вашу способность к обязательствам, настойчивости и дисциплине. Создание собственного списка задач и установление времени для их выполнения — отличный показатель роста. Именно так поступают успешные предприниматели по всему миру.",
    "محتوى الوسائط": "Медиаконтент",
    "اطلع على أحدث المحتوى التعليمي والإعلامي": "Ознакомьтесь с новейшим обучающим и медиаконтентом",

    // ---- Wallet extras (ru) ----
    "انضم إلى": "Присоединяйтесь к",
    "واحصل على مكافآت! استخدم رمز الإحالة:": "и получайте награды! Используйте реферальный код:",
    "تم نسخ رابط المشاركة": "Ссылка скопирована",
    "تسجيل عنوان Solana": "Регистрация адреса Solana",
    "عنوان محفظة Solana": "Адрес кошелька Solana",
    "ادخل عنوان محفظة Solana...": "Введите адрес кошелька Solana...",
    "جاري التسجيل...": "Регистрация...",
    "تسجيل العنوان": "Зарегистрировать адрес",
    "التعدين التالي": "Следующий майнинг",
    "متاح الآن": "Доступно сейчас",
    "مؤشر التعدين EVM": "Индикатор EVM майнинга",
    "جاهز للتعدين": "Готов к майнингу",
    "العنوان المسجل": "Зарегистрированный адрес",
    "Solana Address": "Адрес Solana",
    "الأصل والمصير": "Истоки и Судьба",
    "سيتم مراجعة طلبك من قبل الإدارة، وسيتم إشعارك بالقرار عبر البريد الإلكتروني": "Ваша заявка будет рассмотрена, вы получите уведомление по email",
  },
};

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (arabicText: string, englishText?: string) => string;
  dir: "rtl" | "ltr";
}

const LanguageContext = createContext<LanguageContextType | null>(null);

const DEFAULT_LANGUAGE: AppLanguage = "both";

const isSupportedLanguage = (value: string | null): value is AppLanguage => {
  return !!value && value in SUPPORTED_LANGUAGES;
};

const getInitialLanguage = (): AppLanguage => {
  if (typeof window === "undefined") return DEFAULT_LANGUAGE;
  const storedLanguage = localStorage.getItem("app_language");
  return isSupportedLanguage(storedLanguage) ? storedLanguage : DEFAULT_LANGUAGE;
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>(getInitialLanguage);

  const setLanguage = (lang: AppLanguage) => {
    const safeLanguage = isSupportedLanguage(lang) ? lang : DEFAULT_LANGUAGE;
    setLanguageState(safeLanguage);
    localStorage.setItem("app_language", safeLanguage);
  };

  // RTL for Arabic languages, LTR for others
  const isRtl = language === "ar" || language === "both";
  const dir = isRtl ? "rtl" : "ltr";

  useEffect(() => {
    if (!isSupportedLanguage(localStorage.getItem("app_language"))) {
      localStorage.setItem("app_language", language);
    }
    document.documentElement.dir = dir;
    document.documentElement.lang = language === "both" ? "ar" : language;
    // Update text alignment based on direction
    document.documentElement.style.textAlign = isRtl ? "right" : "left";
  }, [language, dir, isRtl]);

  const t = (arabicText: string, englishText?: string): string => {
    if (language === "both") {
      if (englishText) return `${arabicText} (${englishText})`;
      const enTranslation = translations.en[arabicText];
      if (enTranslation) return `${arabicText} (${enTranslation})`;
      return arabicText;
    }
    if (language === "ar") return arabicText;

    // ابحث في قاموس اللغة الحالية
    const langTranslations = translations[language];
    if (langTranslations && langTranslations[arabicText]) {
      return langTranslations[arabicText];
    }

    // الاحتياط: استخدم الإنجليزية أولاً
    if (language === "en" && englishText) return englishText;
    const enTranslation = translations.en[arabicText];
    if (enTranslation) return enTranslation;

    // الاحتياط النهائي: النص الإنجليزي المعطى أو النص العربي
    return englishText || arabicText;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
