import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type AppLanguage = "both" | "ar" | "en" | "fr" | "es" | "de" | "tr" | "zh" | "hi" | "ru" | "pt" | "ja" | "ko";

interface LanguageLabels {
  native: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: Record<AppLanguage, LanguageLabels> = {
  both: { native: "عربي + English", flag: "🌍" },
  ar: { native: "العربية", flag: "🇪🇬" },
  en: { native: "English", flag: "🇬🇧" },
  fr: { native: "Français", flag: "🇫🇷" },
  es: { native: "Español", flag: "🇪🇸" },
  de: { native: "Deutsch", flag: "🇩🇪" },
  tr: { native: "Türkçe", flag: "🇹🇷" },
  zh: { native: "中文", flag: "🇨🇳" },
  hi: { native: "हिन्दी", flag: "🇮🇳" },
  ru: { native: "Русский", flag: "🇷🇺" },
  pt: { native: "Português", flag: "🇧🇷" },
  ja: { native: "日本語", flag: "🇯🇵" },
  ko: { native: "한국어", flag: "🇰🇷" },
};

type TranslationKey = string;
type Translations = Record<AppLanguage, Record<TranslationKey, string>>;

const translations: Translations = {
  both: {},
  ar: {},
  en: {
    // ---- Navigation ----
    "الرئيسية": "Home",
    "المحفظة": "Wallet",
    "التعلم": "Learning",
    "الاستبيانات": "Surveys",
    "البروفايل": "Profile",
    "تسجيل الخروج": "Sign Out",
    "تسجيل الدخول": "Sign In",
    "انضم الآن": "Join Now",
    "التنقل الرئيسي": "Main Navigation",
    "الوصول المبكر": "Early Access",
    "لوحة التحكم": "Admin Panel",
    "رسالة جديدة": "New Message",
    "البث المباشر": "Live Streams",
    "التعدين": "Mining",
    "الهوية": "Identity",
    "المستندات": "Documents",
    "التحديثات": "Updates",
    "الدعم": "Support",
    "العملة المستقرة": "StableCoin",
    "المهام اليومية": "Daily Tasks",
    "الريلز": "Reels",
    "خريطة الطريق": "Roadmap",
    "أنوبيس": "Anubis",
    "الاشتراك": "Subscription",

    // ---- Platform names ----
    "منصة مصر الرقمية": "Egypt Digital Platform",
    "منصة مصر": "Egypt Platform",
    "مصر": "MSR",

    // ---- Common UI ----
    "جاري التحميل...": "Loading...",
    "جاري التحقق من الصلاحيات...": "Checking permissions...",
    "جاري التحميل": "Loading",
    "يرجى تسجيل الدخول": "Please sign in",
    "للوصول إلى المحفظة": "to access your wallet",
    "غير مصرح": "Unauthorized",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "You don't have permission to access this page",
    "إعادة تحميل الصفحة": "Reload Page",
    "المحاولة مرة أخرى": "Try Again",
    "حدث خطأ غير متوقع": "An unexpected error occurred",
    "عذراً، حدث خطأ في التطبيق. يرجى إعادة تحميل الصفحة.": "Sorry, an error occurred. Please reload the page.",
    "تفاصيل الخطأ": "Error Details",

    // ---- Actions ----
    "حفظ": "Save",
    "إلغاء": "Cancel",
    "تأكيد": "Confirm",
    "إرسال": "Send",
    "تحديث": "Update",
    "حذف": "Delete",
    "إضافة": "Add",
    "تعديل": "Edit",
    "بحث": "Search",
    "عرض": "View",
    "رفع": "Upload",
    "تنزيل": "Download",
    "نسخ": "Copy",
    "مشاركة": "Share",
    "موافق": "OK",
    "رفض": "Reject",
    "قبول": "Accept",

    // ---- Status ----
    "نشط": "Active",
    "غير نشط": "Inactive",
    "معلق": "Pending",
    "مكتمل": "Completed",
    "مرفوض": "Rejected",
    "موافق عليه": "Approved",
    "قيد المراجعة": "Under Review",
    "منتهي": "Expired",

    // ---- Auth page ----
    "إنشاء حساب جديد": "Create New Account",
    "الاسم الكامل": "Full Name",
    "البريد الإلكتروني": "Email",
    "كلمة المرور": "Password",
    "رقم الهاتف": "Phone Number",
    "الدخول بـ Google": "Sign in with Google",
    "ليس لديك حساب؟": "Don't have an account?",
    "لديك حساب بالفعل؟": "Already have an account?",
    "تم تسجيل الدخول بنجاح": "Signed in successfully",
    "مرحباً بك في منصة مصر": "Welcome to Egypt Platform",
    "فشل تسجيل الدخول": "Sign in failed",
    "تحقق من البيانات": "Check your credentials",
    "تم إنشاء الحساب": "Account created",
    "تحقق من بريدك لتفعيل الحساب": "Check your email to activate your account",
    "تعذر إنشاء الحساب": "Failed to create account",

    // ---- Wallet ----
    "الرصيد": "Balance",
    "استقبال": "Receive",
    "تاريخ المعاملات": "Transaction History",
    "المعاملة": "Transaction",
    "المبلغ": "Amount",
    "التاريخ": "Date",
    "الحالة": "Status",
    "عنوان المحفظة": "Wallet Address",
    "شحن المحفظة": "Recharge Wallet",

    // ---- Profile ----
    "تعديل البروفايل": "Edit Profile",
    "الاسم": "Name",
    "البيو": "Bio",
    "المتابعون": "Followers",
    "المتابَعون": "Following",
    "الإنجازات": "Achievements",
    "حساب موثق": "Verified Account",
    "تغيير الصورة": "Change Photo",

    // ---- Mining ----
    "بدء التعدين": "Start Mining",
    "إيقاف التعدين": "Stop Mining",
    "معدل التعدين": "Mining Rate",
    "إجمالي التعدين": "Total Mined",
    "مستوى التعدين": "Mining Level",

    // ---- Support ----
    "إرسال رسالة": "Send Message",
    "موضوع الرسالة": "Subject",
    "نص الرسالة": "Message",
    "الرسائل المرسلة": "Sent Messages",
    "رد الدعم": "Support Reply",

    // ---- Learning ----
    "الدروس": "Lessons",
    "المقالات": "Articles",
    "الفيديوهات": "Videos",
    "اختبار": "Quiz",
    "الدرجة": "Score",
    "اجتاز": "Passed",
    "رسب": "Failed",

    // ---- Surveys ----
    "الاستبيان": "Survey",
    "الأسئلة": "Questions",
    "الإجابات": "Answers",
    "إرسال الاستبيان": "Submit Survey",
    "لم يكتمل": "Incomplete",

    // ---- Early Access ----
    "طلب الوصول المبكر": "Request Early Access",
    "في انتظار الموافقة": "Awaiting Approval",
    "تم قبولك": "You've been accepted",
    "لم تتم الموافقة بعد": "Not approved yet",

    // ---- Live Stream ----
    "بث مباشر": "Live Stream",
    "شاهد البث": "Watch Stream",
    "بدء البث": "Start Streaming",
    "إنهاء البث": "End Stream",
    "المشاهدون": "Viewers",
    "تعليق": "Comment",
    "التعليقات": "Comments",

    // ---- Admin ----
    "إدارة المستخدمين": "Users Management",
    "إدارة الوصول المبكر": "Early Access Management",
    "رسائل الدعم": "Support Messages",
    "إدارة الحسابات المعتمدة": "Verified Accounts",
    "إدارة الهوية": "Identity Management",
    "إدارة الاستبيانات": "Surveys Management",
    "إدارة التعلم": "Learning Management",
    "إدارة محتوى التطبيق": "App Content Management",
    "إدارة التحديثات": "Updates Management",
    "إدارة مستويات التعدين": "Mining Levels Management",
    "إدارة مواقع المتعاونين": "Market Locations Management",
    "إدارة الإعلانات": "Announcements Management",
    "إدارة البادجات": "Badges Management",
    "إدارة كارت أنوبيس": "Anubis Card Management",
    "إدارة الاستدعاء النشط": "Active Callout Management",
    "قائمة الاستدعاء الشرفية": "Honor Callout List",
    "إحصائيات التفاعل": "Engagement Stats",
    "المهام اليومية (إدارة)": "Daily Tasks Management",
    "إدارة صفحات القرآن": "Quran Pages Management",
    "إدارة الوسائط": "Media Management",
    "مهام تطوير الشخصية": "Personality Tasks",
    "إدارة مقدمات المهام": "Task Introductions",
    "إدارة أقسام الريلز": "Reels Categories",
    "إدارة كارت الاستدعاء": "Callout Card Management",
    "إعدادات التحويل": "Conversion Settings",
    "إدارة كروت الرودماب": "Roadmap Cards",
    "إدارة بطاقات الصفحة الرئيسية": "Home Page Cards",
    "إعدادات البروفايل": "Profile Settings",
    "إدارة طلبات البث المباشر": "Live Stream Approvals",
    "إدارة العملات الداخلية": "Internal Tokens",
    "إدارة مجمع السيولة": "Liquidity Pool",
    "إدارة عجلة الحظ": "Wheel of Fortune",
    "إدارة طلبات العائلة": "Family Requests",
    "إدارة رسالة المنصة": "Platform Message",

    // ---- Errors ----
    "خطأ": "Error",
    "حدث خطأ": "An error occurred",
    "فشل في التحميل": "Failed to load",
    "فشل في الحفظ": "Failed to save",
    "فشل في الإرسال": "Failed to send",
    "فشل في تحميل البروفايل": "Failed to load profile",

    // ---- Success ----
    "تم بنجاح": "Done successfully",
    "تم الحفظ": "Saved",
    "تم الإرسال": "Sent",

    // ---- Misc ----
    "الدفع بـ Pi": "Pay with Pi",
    "إعادة الشحن": "Recharge",
    "عجلة الحظ": "Wheel of Fortune",
    "العائلة": "Family",
    "الإعلانات": "Announcements",
    "التوثيق": "Verification",
    "الخصوصية": "Privacy",
    "سياسة الخصوصية": "Privacy Policy",
  },

  fr: {
    "الرئيسية": "Accueil",
    "المحفظة": "Portefeuille",
    "التعلم": "Apprentissage",
    "الاستبيانات": "Sondages",
    "البروفايل": "Profil",
    "تسجيل الخروج": "Déconnexion",
    "تسجيل الدخول": "Connexion",
    "انضم الآن": "Rejoignez",
    "التنقل الرئيسي": "Navigation",
    "الوصول المبكر": "Accès anticipé",
    "لوحة التحكم": "Administration",
    "رسالة جديدة": "Nouveau message",
    "البث المباشر": "Diffusion en direct",
    "التعدين": "Minage",
    "الهوية": "Identité",
    "المستندات": "Documents",
    "التحديثات": "Mises à jour",
    "الدعم": "Support",
    "المهام اليومية": "Tâches quotidiennes",
    "منصة مصر الرقمية": "Plateforme Numérique d'Égypte",
    "منصة مصر": "Plateforme Égypte",
    "مصر": "MSR",
    "جاري التحميل...": "Chargement...",
    "جاري التحقق من الصلاحيات...": "Vérification des autorisations...",
    "يرجى تسجيل الدخول": "Veuillez vous connecter",
    "غير مصرح": "Non autorisé",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "Vous n'avez pas la permission d'accéder à cette page",
    "حفظ": "Enregistrer",
    "إلغاء": "Annuler",
    "تأكيد": "Confirmer",
    "إرسال": "Envoyer",
    "تعديل": "Modifier",
    "حذف": "Supprimer",
    "إضافة": "Ajouter",
    "بحث": "Rechercher",
    "الرصيد": "Solde",
    "تاريخ المعاملات": "Historique",
    "البريد الإلكتروني": "Email",
    "كلمة المرور": "Mot de passe",
    "الاسم الكامل": "Nom complet",
    "إنشاء حساب جديد": "Créer un compte",
    "خطأ": "Erreur",
    "تم بنجاح": "Succès",
    "سياسة الخصوصية": "Politique de confidentialité",
    "الدفع بـ Pi": "Payer avec Pi",
  },

  es: {
    "الرئيسية": "Inicio",
    "المحفظة": "Billetera",
    "التعلم": "Aprendizaje",
    "الاستبيانات": "Encuestas",
    "البروفايل": "Perfil",
    "تسجيل الخروج": "Cerrar sesión",
    "تسجيل الدخول": "Iniciar sesión",
    "انضم الآن": "Únete ahora",
    "التنقل الرئيسي": "Navegación",
    "الوصول المبكر": "Acceso anticipado",
    "لوحة التحكم": "Administración",
    "رسالة جديدة": "Nuevo mensaje",
    "البث المباشر": "Transmisión en vivo",
    "التعدين": "Minería",
    "الهوية": "Identidad",
    "المستندات": "Documentos",
    "التحديثات": "Actualizaciones",
    "الدعم": "Soporte",
    "المهام اليومية": "Tareas diarias",
    "منصة مصر الرقمية": "Plataforma Digital de Egipto",
    "منصة مصر": "Plataforma Egipto",
    "مصر": "MSR",
    "جاري التحميل...": "Cargando...",
    "جاري التحقق من الصلاحيات...": "Verificando permisos...",
    "يرجى تسجيل الدخول": "Por favor, inicia sesión",
    "غير مصرح": "No autorizado",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "No tienes permiso para acceder a esta página",
    "حفظ": "Guardar",
    "إلغاء": "Cancelar",
    "تأكيد": "Confirmar",
    "إرسال": "Enviar",
    "تعديل": "Editar",
    "حذف": "Eliminar",
    "إضافة": "Añadir",
    "بحث": "Buscar",
    "الرصيد": "Saldo",
    "البريد الإلكتروني": "Correo electrónico",
    "كلمة المرور": "Contraseña",
    "الاسم الكامل": "Nombre completo",
    "إنشاء حساب جديد": "Crear nueva cuenta",
    "خطأ": "Error",
    "تم بنجاح": "Éxito",
    "سياسة الخصوصية": "Política de privacidad",
    "الدفع بـ Pi": "Pagar con Pi",
  },

  de: {
    "الرئيسية": "Startseite",
    "المحفظة": "Brieftasche",
    "التعلم": "Lernen",
    "الاستبيانات": "Umfragen",
    "البروفايل": "Profil",
    "تسجيل الخروج": "Abmelden",
    "تسجيل الدخول": "Anmelden",
    "انضم الآن": "Jetzt beitreten",
    "التنقل الرئيسي": "Navigation",
    "الوصول المبكر": "Frühzeitiger Zugang",
    "لوحة التحكم": "Verwaltung",
    "رسالة جديدة": "Neue Nachricht",
    "البث المباشر": "Livestream",
    "التعدين": "Mining",
    "الهوية": "Identität",
    "المستندات": "Dokumente",
    "التحديثات": "Updates",
    "الدعم": "Support",
    "المهام اليومية": "Tägliche Aufgaben",
    "منصة مصر الرقمية": "Ägyptens Digitale Plattform",
    "مصر": "MSR",
    "جاري التحميل...": "Laden...",
    "جاري التحقق من الصلاحيات...": "Berechtigungen werden geprüft...",
    "يرجى تسجيل الدخول": "Bitte melden Sie sich an",
    "غير مصرح": "Nicht autorisiert",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "Sie haben keine Berechtigung, auf diese Seite zuzugreifen",
    "حفظ": "Speichern",
    "إلغاء": "Abbrechen",
    "تأكيد": "Bestätigen",
    "إرسال": "Senden",
    "تعديل": "Bearbeiten",
    "حذف": "Löschen",
    "إضافة": "Hinzufügen",
    "بحث": "Suchen",
    "البريد الإلكتروني": "E-Mail",
    "كلمة المرور": "Passwort",
    "الاسم الكامل": "Vollständiger Name",
    "خطأ": "Fehler",
    "تم بنجاح": "Erfolgreich",
    "سياسة الخصوصية": "Datenschutzrichtlinie",
    "الدفع بـ Pi": "Mit Pi bezahlen",
  },

  tr: {
    "الرئيسية": "Ana Sayfa",
    "المحفظة": "Cüzdan",
    "التعلم": "Öğrenme",
    "الاستبيانات": "Anketler",
    "البروفايل": "Profil",
    "تسجيل الخروج": "Çıkış Yap",
    "تسجيل الدخول": "Giriş Yap",
    "انضم الآن": "Şimdi Katıl",
    "التنقل الرئيسي": "Ana Navigasyon",
    "الوصول المبكر": "Erken Erişim",
    "لوحة التحكم": "Yönetim Paneli",
    "رسالة جديدة": "Yeni Mesaj",
    "البث المباشر": "Canlı Yayın",
    "التعدين": "Madencilik",
    "الهوية": "Kimlik",
    "المستندات": "Belgeler",
    "التحديثات": "Güncellemeler",
    "الدعم": "Destek",
    "المهام اليومية": "Günlük Görevler",
    "منصة مصر الرقمية": "Mısır Dijital Platformu",
    "مصر": "MSR",
    "جاري التحميل...": "Yükleniyor...",
    "جاري التحقق من الصلاحيات...": "İzinler kontrol ediliyor...",
    "يرجى تسجيل الدخول": "Lütfen giriş yapın",
    "غير مصرح": "Yetkisiz",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "Bu sayfaya erişim izniniz yok",
    "حفظ": "Kaydet",
    "إلغاء": "İptal",
    "تأكيد": "Onayla",
    "إرسال": "Gönder",
    "تعديل": "Düzenle",
    "حذف": "Sil",
    "إضافة": "Ekle",
    "بحث": "Ara",
    "البريد الإلكتروني": "E-posta",
    "كلمة المرور": "Şifre",
    "الاسم الكامل": "Tam Ad",
    "خطأ": "Hata",
    "تم بنجاح": "Başarılı",
    "سياسة الخصوصية": "Gizlilik Politikası",
    "الدفع بـ Pi": "Pi ile Öde",
  },

  zh: {
    "الرئيسية": "首页",
    "المحفظة": "钱包",
    "التعلم": "学习",
    "الاستبيانات": "调查",
    "البروفايل": "个人资料",
    "تسجيل الخروج": "退出登录",
    "تسجيل الدخول": "登录",
    "انضم الآن": "立即加入",
    "التنقل الرئيسي": "主导航",
    "الوصول المبكر": "提前访问",
    "لوحة التحكم": "管理面板",
    "رسالة جديدة": "新消息",
    "البث المباشر": "直播",
    "التعدين": "挖矿",
    "الهوية": "身份",
    "المستندات": "文件",
    "التحديثات": "更新",
    "الدعم": "支持",
    "المهام اليومية": "每日任务",
    "منصة مصر الرقمية": "埃及数字平台",
    "مصر": "MSR",
    "جاري التحميل...": "加载中...",
    "جاري التحقق من الصلاحيات...": "正在验证权限...",
    "يرجى تسجيل الدخول": "请登录",
    "غير مصرح": "未授权",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "您没有访问此页面的权限",
    "حفظ": "保存",
    "إلغاء": "取消",
    "تأكيد": "确认",
    "إرسال": "发送",
    "تعديل": "编辑",
    "حذف": "删除",
    "إضافة": "添加",
    "بحث": "搜索",
    "الرصيد": "余额",
    "البريد الإلكتروني": "电子邮件",
    "كلمة المرور": "密码",
    "الاسم الكامل": "全名",
    "خطأ": "错误",
    "تم بنجاح": "成功",
    "سياسة الخصوصية": "隐私政策",
    "الدفع بـ Pi": "用Pi支付",
  },

  hi: {
    "الرئيسية": "होम",
    "المحفظة": "वॉलेट",
    "التعلم": "सीखना",
    "الاستبيانات": "सर्वेक्षण",
    "البروفايل": "प्रोफ़ाइल",
    "تسجيل الخروج": "लॉग आउट",
    "تسجيل الدخول": "लॉग इन",
    "انضم الآن": "अभी जुड़ें",
    "التنقل الرئيسي": "मुख्य नेविगेशन",
    "الوصول المبكر": "जल्दी पहुँच",
    "لوحة التحكم": "एडमिन पैनल",
    "رسالة جديدة": "नया संदेश",
    "البث المباشر": "लाइव स्ट्रीम",
    "التعدين": "माइनिंग",
    "الهوية": "पहचान",
    "المستندات": "दस्तावेज़",
    "التحديثات": "अपडेट",
    "الدعم": "सहायता",
    "المهام اليومية": "दैनिक कार्य",
    "منصة مصر الرقمية": "मिस्र डिजिटल प्लेटफ़ॉर्म",
    "مصر": "MSR",
    "جاري التحميل...": "लोड हो रहा है...",
    "جاري التحقق من الصلاحيات...": "अनुमति जाँची जा रही है...",
    "يرجى تسجيل الدخول": "कृपया लॉग इन करें",
    "غير مصرح": "अनधिकृत",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "आपको इस पृष्ठ तक पहुँचने की अनुमति नहीं है",
    "حفظ": "सहेजें",
    "إلغاء": "रद्द करें",
    "تأكيد": "पुष्टि करें",
    "إرسال": "भेजें",
    "تعديل": "संपादित करें",
    "حذف": "हटाएं",
    "إضافة": "जोड़ें",
    "بحث": "खोजें",
    "البريد الإلكتروني": "ईमेल",
    "كلمة المرور": "पासवर्ड",
    "الاسم الكامل": "पूरा नाम",
    "خطأ": "त्रुटि",
    "تم بنجاح": "सफल",
    "سياسة الخصوصية": "गोपनीयता नीति",
    "الدفع بـ Pi": "Pi से भुगतान करें",
  },

  ru: {
    "الرئيسية": "Главная",
    "المحفظة": "Кошелёк",
    "التعلم": "Обучение",
    "الاستبيانات": "Опросы",
    "البروفايل": "Профиль",
    "تسجيل الخروج": "Выйти",
    "تسجيل الدخول": "Войти",
    "انضم الآن": "Присоединиться",
    "التنقل الرئيسي": "Навигация",
    "الوصول المبكر": "Ранний доступ",
    "لوحة التحكم": "Панель управления",
    "رسالة جديدة": "Новое сообщение",
    "البث المباشر": "Прямой эфир",
    "التعدين": "Майнинг",
    "الهوية": "Удостоверение",
    "المستندات": "Документы",
    "التحديثات": "Обновления",
    "الدعم": "Поддержка",
    "المهام اليومية": "Ежедневные задачи",
    "منصة مصر الرقمية": "Цифровая платформа Египта",
    "مصر": "MSR",
    "جاري التحميل...": "Загрузка...",
    "جاري التحقق من الصلاحيات...": "Проверка разрешений...",
    "يرجى تسجيل الدخول": "Пожалуйста, войдите",
    "غير مصرح": "Нет доступа",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "У вас нет разрешения на доступ к этой странице",
    "حفظ": "Сохранить",
    "إلغاء": "Отмена",
    "تأكيد": "Подтвердить",
    "إرسال": "Отправить",
    "تعديل": "Редактировать",
    "حذف": "Удалить",
    "إضافة": "Добавить",
    "بحث": "Поиск",
    "الرصيد": "Баланс",
    "البريد الإلكتروني": "Email",
    "كلمة المرور": "Пароль",
    "الاسم الكامل": "Полное имя",
    "خطأ": "Ошибка",
    "تم بنجاح": "Успешно",
    "سياسة الخصوصية": "Политика конфиденциальности",
    "الدفع بـ Pi": "Оплатить Pi",
  },

  pt: {
    "الرئيسية": "Início",
    "المحفظة": "Carteira",
    "التعلم": "Aprendizado",
    "الاستبيانات": "Pesquisas",
    "البروفايل": "Perfil",
    "تسجيل الخروج": "Sair",
    "تسجيل الدخول": "Entrar",
    "انضم الآن": "Junte-se agora",
    "التنقل الرئيسي": "Navegação",
    "الوصول المبكر": "Acesso antecipado",
    "لوحة التحكم": "Painel admin",
    "رسالة جديدة": "Nova mensagem",
    "البث المباشر": "Transmissão ao vivo",
    "التعدين": "Mineração",
    "الهوية": "Identidade",
    "المستندات": "Documentos",
    "التحديثات": "Atualizações",
    "الدعم": "Suporte",
    "المهام اليومية": "Tarefas diárias",
    "منصة مصر الرقمية": "Plataforma Digital do Egito",
    "مصر": "MSR",
    "جاري التحميل...": "Carregando...",
    "جاري التحقق من الصلاحيات...": "Verificando permissões...",
    "يرجى تسجيل الدخول": "Por favor, faça login",
    "غير مصرح": "Não autorizado",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "Você não tem permissão para acessar esta página",
    "حفظ": "Salvar",
    "إلغاء": "Cancelar",
    "تأكيد": "Confirmar",
    "إرسال": "Enviar",
    "تعديل": "Editar",
    "حذف": "Excluir",
    "إضافة": "Adicionar",
    "بحث": "Pesquisar",
    "البريد الإلكتروني": "Email",
    "كلمة المرور": "Senha",
    "الاسم الكامل": "Nome completo",
    "خطأ": "Erro",
    "تم بنجاح": "Sucesso",
    "سياسة الخصوصية": "Política de privacidade",
    "الدفع بـ Pi": "Pagar com Pi",
  },

  ja: {
    "الرئيسية": "ホーム",
    "المحفظة": "ウォレット",
    "التعلم": "学習",
    "الاستبيانات": "アンケート",
    "البروفايل": "プロフィール",
    "تسجيل الخروج": "ログアウト",
    "تسجيل الدخول": "ログイン",
    "انضم الآن": "今すぐ参加",
    "التنقل الرئيسي": "メインナビゲーション",
    "الوصول المبكر": "早期アクセス",
    "لوحة التحكم": "管理パネル",
    "رسالة جديدة": "新しいメッセージ",
    "البث المباشر": "ライブ配信",
    "التعدين": "マイニング",
    "الهوية": "身分証明",
    "المستندات": "ドキュメント",
    "التحديثات": "アップデート",
    "الدعم": "サポート",
    "المهام اليومية": "デイリータスク",
    "منصة مصر الرقمية": "エジプトデジタルプラットフォーム",
    "مصر": "MSR",
    "جاري التحميل...": "読み込み中...",
    "جاري التحقق من الصلاحيات...": "権限を確認中...",
    "يرجى تسجيل الدخول": "ログインしてください",
    "غير مصرح": "権限なし",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "このページへのアクセス権限がありません",
    "حفظ": "保存",
    "إلغاء": "キャンセル",
    "تأكيد": "確認",
    "إرسال": "送信",
    "تعديل": "編集",
    "حذف": "削除",
    "إضافة": "追加",
    "بحث": "検索",
    "البريد الإلكتروني": "メール",
    "كلمة المرور": "パスワード",
    "الاسم الكامل": "フルネーム",
    "خطأ": "エラー",
    "تم بنجاح": "成功",
    "سياسة الخصوصية": "プライバシーポリシー",
    "الدفع بـ Pi": "Piで支払う",
  },

  ko: {
    "الرئيسية": "홈",
    "المحفظة": "지갑",
    "التعلم": "학습",
    "الاستبيانات": "설문조사",
    "البروفايل": "프로필",
    "تسجيل الخروج": "로그아웃",
    "تسجيل الدخول": "로그인",
    "انضم الآن": "지금 가입",
    "التنقل الرئيسي": "메인 내비게이션",
    "الوصول المبكر": "조기 접근",
    "لوحة التحكم": "관리자 패널",
    "رسالة جديدة": "새 메시지",
    "البث المباشر": "라이브 스트림",
    "التعدين": "채굴",
    "الهوية": "신원",
    "المستندات": "문서",
    "التحديثات": "업데이트",
    "الدعم": "지원",
    "المهام اليومية": "일일 과제",
    "منصة مصر الرقمية": "이집트 디지털 플랫폼",
    "مصر": "MSR",
    "جاري التحميل...": "로딩 중...",
    "جاري التحقق من الصلاحيات...": "권한 확인 중...",
    "يرجى تسجيل الدخول": "로그인 해주세요",
    "غير مصرح": "권한 없음",
    "ليس لديك صلاحية للوصول إلى هذه الصفحة": "이 페이지에 접근할 권한이 없습니다",
    "حفظ": "저장",
    "إلغاء": "취소",
    "تأكيد": "확인",
    "إرسال": "전송",
    "تعديل": "편집",
    "حذف": "삭제",
    "إضافة": "추가",
    "بحث": "검색",
    "البريد الإلكتروني": "이메일",
    "كلمة المرور": "비밀번호",
    "الاسم الكامل": "전체 이름",
    "خطأ": "오류",
    "تم بنجاح": "성공",
    "سياسة الخصوصية": "개인정보 처리방침",
    "الدفع بـ Pi": "Pi로 결제",
  },
};

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (arabicText: string, englishText?: string) => string;
  dir: "rtl" | "ltr";
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>(() => {
    return (localStorage.getItem("app_language") as AppLanguage) || "both";
  });

  const setLanguage = (lang: AppLanguage) => {
    setLanguageState(lang);
    localStorage.setItem("app_language", lang);
  };

  // دائماً RTL لأن التطبيق مصمم عربياً أولاً
  const dir = "rtl" as const;

  useEffect(() => {
    document.documentElement.dir = "rtl";
    document.documentElement.lang = language === "both" ? "ar" : language;
  }, [language]);

  const t = (arabicText: string, englishText?: string): string => {
    if (language === "both") {
      if (englishText) return `${arabicText} (${englishText})`;
      // في الوضع الثنائي نحاول إيجاد ترجمة إنجليزية للعرض
      const enTranslation = translations.en[arabicText];
      if (enTranslation) return `${arabicText} (${enTranslation})`;
      return arabicText;
    }
    if (language === "ar") return arabicText;

    // ابحث في قاموس اللغة الحالية
    const langTranslations = translations[language];
    if (langTranslations && langTranslations[arabicText]) {
      return langTranslations[arabicText];
    }

    // الاحتياط: استخدم الإنجليزية أولاً
    if (language === "en" && englishText) return englishText;
    const enTranslation = translations.en[arabicText];
    if (enTranslation) return enTranslation;

    // الاحتياط النهائي: النص الإنجليزي المعطى أو النص العربي
    return englishText || arabicText;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
