// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnwfnziozwarlihrnjex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indud2ZuemlvendhcmxpaHJuamV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTU5ODQsImV4cCI6MjA3MDU3MTk4NH0.io-XI4Ygzjgm5qbMassx44wFxZc_czECCJPRM3lHUC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});