// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://wnwfnziozwarlihrnjex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indud2ZuemlvendhcmxpaHJuamV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTU5ODQsImV4cCI6MjA3MDU3MTk4NH0.io-XI4Ygzjgm5qbMassx44wFxZc_czECCJPRM3lHUC0";

const createMissingSupabaseClient = (): SupabaseClient<Database> => {
  const missingConfigError = new Error(
    'Supabase environment variables are missing. Please check your .env file.'
  );

  const createQueryBuilder = (defaultData: unknown = []) => {
    const response = { data: defaultData, error: missingConfigError };
    const promise = Promise.resolve(response);

    return new Proxy(
      {},
      {
        get(_, prop) {
          if (prop === 'then') return promise.then.bind(promise);
          if (prop === 'catch') return promise.catch.bind(promise);
          if (prop === 'finally') return promise.finally.bind(promise);
          if (prop === 'single' || prop === 'maybeSingle') {
            return () => createQueryBuilder(null);
          }
          return () => createQueryBuilder(defaultData);
        },
      }
    );
  };

  const createChannel = () => {
    const channel = {
      on: () => channel,
      subscribe: () => ({ unsubscribe: () => undefined }),
    };

    return channel;
  };

  console.error(missingConfigError.message);

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({
        data: { subscription: { unsubscribe: () => undefined } },
      }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error: missingConfigError }),
      signUp: async () => ({ data: { user: null, session: null }, error: missingConfigError }),
      signInWithOAuth: async () => ({ data: null, error: missingConfigError }),
      signOut: async () => ({ error: null }),
    },
    from: () => createQueryBuilder(),
    rpc: async () => ({ data: null, error: missingConfigError }),
    channel: () => createChannel(),
    removeChannel: async () => ({ data: null, error: null }),
    functions: {
      invoke: async () => ({ data: null, error: missingConfigError }),
    },
    storage: {
      from: () => ({
        remove: async () => ({ data: null, error: missingConfigError }),
      }),
    },
  } as unknown as SupabaseClient<Database>;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: SupabaseClient<Database> = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createMissingSupabaseClient();